namespace AbCatDC.RazorLib.Shared;

/// <summary>
/// Ready-made example palettes: small curated rule systems the user can load
/// into the rule editor as a starting point. Schematic where the kernel's
/// syntax lacks a native notion (noted in the descriptions).
/// </summary>
public static class ExampleSystems
{
    public record ExampleSystem(
        string Name, string Description, RulePalette.Entry[] Rules,
        (string Name, string Json)[]? Sketches = null);

    static RulePalette.Entry R(string kind, string name, string[] prem, string[] concl, string desc) =>
        new(kind, name, prem, concl, desc);

    static readonly string[] None = System.Array.Empty<string>();

    public static readonly ExampleSystem[] All =
    {
        new("Simply typed λ-calculus",
            "The minimal functional core in sequent style, with typing judgments t : T throughout.",
            new[]
            {
                R("Structural", "var", None, new[] { "Γ, x : σ ⊢ x : σ" },
                    "Variable rule: a hypothesis proves itself."),
                R("Introduction", "→-intro", new[] { "Γ, x : σ ⊢ M : τ" }, new[] { "Γ ⊢ λxM : σ → τ" },
                    "Abstraction: discharge the hypothesis x : σ; λxM stands for λx. M."),
                R("Elimination", "→-elim", new[] { "Γ ⊢ f : σ → τ", "Γ ⊢ a : σ" }, new[] { "Γ ⊢ fa : τ" },
                    "Application: fa stands for f a."),
                R("Computational", "β-compute", new[] { "Γ, x : σ ⊢ M : τ", "Γ ⊢ a : σ" }, new[] { "Γ ⊢ Mxa : τ" },
                    "β-reduction: (λx. M) a ↝ M[x := a]; Mxa stands for the substituted body."),
                R("Introduction", "×-intro", new[] { "Γ ⊢ M : σ", "Γ ⊢ N : τ" }, new[] { "Γ ⊢ MN : σ × τ" },
                    "Pairing: MN stands for the pair (M, N)."),
                R("Elimination", "×-proj1", new[] { "Γ ⊢ p : σ × τ" }, new[] { "Γ ⊢ p1 : σ" },
                    "First projection: p1 stands for π₁ p."),
                R("Elimination", "×-proj2", new[] { "Γ ⊢ p : σ × τ" }, new[] { "Γ ⊢ p2 : τ" },
                    "Second projection: p2 stands for π₂ p."),
            }),

        new("System F",
            "Girard/Reynolds polymorphism in sequent style with typing judgments.",
            new[]
            {
                R("Structural", "var", None, new[] { "Γ, x : σ ⊢ x : σ" }, "Variable rule."),
                R("Introduction", "→-intro", new[] { "Γ, x : σ ⊢ M : τ" }, new[] { "Γ ⊢ λxM : σ → τ" },
                    "Term abstraction, discharging x : σ."),
                R("Elimination", "→-elim", new[] { "Γ ⊢ f : σ → τ", "Γ ⊢ a : σ" }, new[] { "Γ ⊢ fa : τ" },
                    "Term application."),
                R("Introduction", "∀-intro", new[] { "Γ ⊢ M : τ" }, new[] { "Γ ⊢ M : ∀α. τ" },
                    "Type abstraction Λα. M — side condition: α not free in Γ."),
                R("Elimination", "∀-elim", new[] { "Γ ⊢ M : ∀α. τ" }, new[] { "Γ ⊢ M : τ" },
                    "Type application: the conclusion is at τ[α := σ] for any chosen σ."),
                R("Computational", "Λβ-compute", new[] { "Γ ⊢ M : ∀α. τ" }, new[] { "Γ ⊢ M : τ" },
                    "Type-level β: (Λα. M)[σ] ↝ M[α := σ]."),
                R("Introduction", "church-two", None, new[] { "⊢ c2 : ∀α. (α → α) → α → α" },
                    "A closed inhabitant: the Church numeral 2 = λf. λx. f (f x), typed in the empty context."),
            }),

        new("Martin-Löf type theory",
            "Dependent Π and Σ over ℕ with the induction principle.",
            new[]
            {
                R("Structural", "var", None, new[] { "Γ, x : σ ⊢ x : σ" }, "Variable rule."),
                R("Introduction", "Π-intro", new[] { "Γ, x : σ ⊢ M : τ" }, new[] { "Γ ⊢ λxM : (x : σ) → τ" },
                    "Dependent abstraction over the hypothesis x : σ."),
                R("Elimination", "Π-elim", new[] { "Γ ⊢ f : (x : σ) → τ", "Γ ⊢ a : σ" }, new[] { "Γ ⊢ fa : τ" },
                    "Dependent application: the result type is τ[x := a]."),
                R("Introduction", "Σ-intro", new[] { "Γ ⊢ a : σ", "Γ ⊢ b : τ" }, new[] { "Γ ⊢ ab : (x : σ) × τ" },
                    "Dependent pairing: witness a with proof b of τ[x := a]."),
                R("Elimination", "Σ-proj1", new[] { "Γ ⊢ p : (x : σ) × τ" }, new[] { "Γ ⊢ p1 : σ" },
                    "First projection: the witness."),
                R("Elimination", "Σ-proj2", new[] { "Γ ⊢ p : (x : σ) × τ" }, new[] { "Γ ⊢ p2 : τ" },
                    "Second projection, at type τ[x := π₁ p]."),
                R("Construction", "ℕ-zero", None, new[] { "⊢ 0 : ℕ" }, "Zero, in the empty context."),
                R("Construction", "ℕ-succ", new[] { "Γ ⊢ n : ℕ" }, new[] { "Γ ⊢ n + 1 : ℕ" }, "Successor."),
                R("Elimination", "ℕ-ind",
                    new[] { "Γ ⊢ z : ρ", "Γ ⊢ s : (n : ℕ) → ρ → ρ", "Γ ⊢ m : ℕ" }, new[] { "Γ ⊢ r : ρ" },
                    "Induction / recursion: r stands for ind(z, s, m) — base case z, step s, applied to m."),
            }),

        new("Cubical type theory",
            "Schematic cubical primitives: the interval I, paths as functions out of it, transport and composition.",
            new[]
            {
                R("Construction", "I-0", None, new[] { "0" },
                    "The left endpoint of the interval I (rendered as the numeral 0)."),
                R("Construction", "I-1", None, new[] { "1" },
                    "The right endpoint of the interval I."),
                R("Introduction", "Path-intro", new[] { "τ" }, new[] { "(i : I) → τ" },
                    "A path is a function out of the interval: λi. M, with M possibly mentioning i."),
                R("Elimination", "Path-app", new[] { "(i : I) → τ", "I" }, new[] { "τ" },
                    "Evaluate a path at an interval point; the endpoints give the two sides of the equality."),
                R("Construction", "refl", new[] { "σ" }, new[] { "(i : I) → σ" },
                    "The constant path at a point — reflexivity."),
                R("Computational", "transp", new[] { "(i : I) → τ" }, new[] { "τ → τ" },
                    "Transport along a line of types: coerce the fiber at 0 into the fiber at 1."),
                R("Computational", "hcomp", new[] { "σ", "(i : I) → σ" }, new[] { "σ" },
                    "Homogeneous composition: cap an open box in σ."),
                R("Computational", "funext", new[] { "(x : σ) → (i : I) → τ" }, new[] { "(i : I) → (x : σ) → τ" },
                    "Function extensionality: a family of paths swaps into a path of functions."),
                R("Computational", "conn-meet", new[] { "I", "I" }, new[] { "I" },
                    "Connection i ∧ j: the meet operation on the interval."),
                R("Computational", "conn-join", new[] { "I", "I" }, new[] { "I" },
                    "Connection i ∨ j: the join operation on the interval."),
                R("Computational", "ua", new[] { "σ → τ", "τ → σ" }, new[] { "(i : I) → σ ∪ τ" },
                    "Univalence, schematically: an equivalence between σ and τ yields a line of types between them."),
            }),

        new("Peano arithmetic",
            "ℤ-flavored arithmetic: zero, successor, the defining equations of addition, and induction.",
            new[]
            {
                R("Construction", "zero", None, new[] { "0" }, "The numeral 0 : ℕ."),
                R("Construction", "succ", new[] { "n" }, new[] { "n + 1" },
                    "Successor: n ↦ n + 1, computing in ℤ."),
                R("Computational", "add-zero", new[] { "n + 0" }, new[] { "n" },
                    "Defining equation: n + 0 = n."),
                R("Computational", "add-succ", new[] { "n + (m + 1)" }, new[] { "(n + m) + 1" },
                    "Defining equation: n + s(m) = s(n + m)."),
                R("Computational", "ℤ-add-2+2", new[] { "2 + 2" }, new[] { "4" },
                    "A closed instance: 2 + 2 computes to 4 in ℤ."),
                R("Elimination", "ℕ-ind", new[] { "ρ", "(n : ℕ) → ρ → ρ", "ℕ" }, new[] { "ρ" },
                    "Induction: ρ(0) and ∀n. ρ(n) → ρ(n+1) give ρ for every natural number."),
            }),

        new("Intersection types",
            "The intersection type discipline — the system whose typable terms are exactly the strongly normalizing ones.",
            new[]
            {
                R("Introduction", "∩-intro", new[] { "σ", "τ" }, new[] { "σ ∩ τ" },
                    "One and the same term must inhabit both types."),
                R("Elimination", "∩-elim1", new[] { "σ ∩ τ" }, new[] { "σ" }, "Left component."),
                R("Elimination", "∩-elim2", new[] { "σ ∩ τ" }, new[] { "τ" }, "Right component."),
                R("Computational", "∩-idem", new[] { "σ ∩ σ" }, new[] { "σ" }, "Idempotence."),
                R("Computational", "∩-comm", new[] { "σ ∩ τ" }, new[] { "τ ∩ σ" }, "Commutativity."),
                R("Elimination", "∩-mono", new[] { "A → B" }, new[] { "(A ∩ X) → (B ∩ X)" },
                    "Monotonicity of intersection in a subtyping reading."),
                R("Elimination", "→-elim", new[] { "σ → τ", "σ" }, new[] { "τ" }, "Application."),
            }),

        new("Abelian categories",
            "The definitional tower of an abelian category, as diagrammatically as the language allows: hom-sets are abelian groups (composition bilinear), there is a zero object [Zero], every pair has a biproduct [Biprod], every morphism has a kernel [Ker] and cokernel [Coker] with their universal properties [KerUniv], and the abelian axioms make every mono a kernel and every epi a cokernel. Additive functors preserve the structure. (The remaining axiom — the canonical map coim f → im f is an isomorphism — needs image factorizations and is stated here only as this note.)",
            new[]
            {
                R("Construction", "hom-add",
                    new[] { "Γ ⊢ f : A → B", "Γ ⊢ g : A → B" }, new[] { "Γ ⊢ f + g : A → B" },
                    "Ab-enrichment: parallel morphisms add — hom(A, B) is an abelian group."),
                R("Construction", "hom-zero", None,
                    new[] { "C : Type, A : C, B : C ⊢ 0 : A → B" },
                    "Every hom-group has its zero element: the zero morphism, written literally 0."),
                R("Construction", "hom-neg",
                    new[] { "Γ ⊢ f : A → B" }, new[] { "Γ ⊢ ⋃(g:A → B) (g + f = 0)" },
                    "Additive inverses: for every f there exists g (= −f) with g + f = 0."),
                R("Computational", "comp-bilinear",
                    new[] { "Γ ⊢ h : B → D", "Γ ⊢ f : A → B", "Γ ⊢ g : A → B", "Γ ⊢ s = f + g" },
                    new[] { "Γ ⊢ hs = hf + hg" },
                    "Composition is bilinear over addition, left law: h∘(f + g) = h∘f + h∘g (juxtaposition is composition). The typings keep f, g, s in the hom-set composable with h."),
                R("Computational", "comp-bilinear-r",
                    new[] { "Γ ⊢ e : E → A", "Γ ⊢ f : A → B", "Γ ⊢ g : A → B", "Γ ⊢ s = f + g" },
                    new[] { "Γ ⊢ se = fe + ge" },
                    "Bilinearity, right law: (f + g)∘e = f∘e + g∘e."),
                R("Structural", "zero-object", None,
                    new[] { "C : Type, X : C, Y : C ⊢ [Zero] commutes" },
                    "There is a zero object 0, initial and terminal: t : X → 0 and s : 0 → Y are the unique such maps, and the diagram commuting says the zero morphism X → Y is exactly s∘t."),
                R("Construction", "biproduct", None,
                    new[] { "C : Type, A : C, B : C ⊢ [Biprod] in C",
                            "C : Type, A : C, B : C ⊢ i₁ : A → S",
                            "C : Type, A : C, B : C ⊢ i₂ : B → S",
                            "C : Type, A : C, B : C ⊢ p₁ : S → A",
                            "C : Type, A : C, B : C ⊢ p₂ : S → B",
                            "C : Type, A : C, B : C ⊢ p₁i₁ = 1ₐ",
                            "C : Type, A : C, B : C ⊢ p₂i₂ = 1ᵦ",
                            "C : Type, A : C, B : C ⊢ i₁p₁ + i₂p₂ = 1ₛ" },
                    "Every pair has a biproduct A ⊕ B, here introduced as the fresh object S with injections i₁, i₂ and projections p₁, p₂ satisfying p₁i₁ = 1ₐ, p₂i₂ = 1ᵦ, and the characteristic identity i₁p₁ + i₂p₂ = 1ₛ — product and coproduct at once, courtesy of the additive structure. (1ₓ names are rigid identity notation.)"),
                R("Construction", "kernel",
                    new[] { "Γ ⊢ f : A → B" },
                    new[] { "Γ ⊢ k : Ker f", "Γ ⊢ k : K → A", "Γ ⊢ fk = 0", "Γ ⊢ [Ker] commutes" },
                    "Every morphism has a kernel: k : K → A with f∘k = 0. The judgment k : Ker f is the marker 'k is a kernel of f' — it is what licenses the universal property below."),
                R("Elimination", "kernel-universal",
                    new[] { "Γ ⊢ k : Ker f", "Γ ⊢ k : K → A", "Γ ⊢ t : T → A", "Γ ⊢ ft = 0" },
                    new[] { "Γ ⊢ ⋃(u:T → K) (ku = t)", "Γ ⊢ [KerUniv] commutes" },
                    "The kernel's universal property: any t with f∘t = 0 factors uniquely through K — the dashed u in the diagram, with k∘u = t. Note the hypothesis k : Ker f — without it, this would let t factor through an arbitrary k."),
                R("Construction", "cokernel",
                    new[] { "Γ ⊢ f : A → B" },
                    new[] { "Γ ⊢ c : Coker f", "Γ ⊢ c : B → Q", "Γ ⊢ cf = 0", "Γ ⊢ [Coker] commutes" },
                    "Dually, every morphism has a cokernel: c : B → Q with c∘f = 0, marked by c : Coker f."),
                R("Structural", "ker-mono",
                    new[] { "Γ ⊢ k : Ker f" }, new[] { "Γ ⊢ k : Mono" },
                    "Kernels are monic — the introduction rule for the class judgment Mono: if k∘u = k∘v then f∘(ku) = 0 = f∘(kv), and both factor uniquely through k, so u = v."),
                R("Structural", "coker-epi",
                    new[] { "Γ ⊢ c : Coker f" }, new[] { "Γ ⊢ c : Epi" },
                    "Cokernels are epic — dually, the introduction rule for Epi."),
                R("Elimination", "mono-cancel",
                    new[] { "Γ ⊢ m : Mono", "Γ ⊢ m : A → B", "Γ ⊢ u : T → A", "Γ ⊢ v : T → A", "Γ ⊢ mu = mv" },
                    new[] { "Γ ⊢ u = v", "Γ ⊢ [Mono] commutes" },
                    "Monomorphism cancellation — the elimination rule for the class judgment m : Mono: given m∘u = m∘v the parallel pair collapses to u = v, which is exactly what [Mono] commuting asserts. Being mono MEANS admitting this rule."),
                R("Elimination", "epi-cancel",
                    new[] { "Γ ⊢ e : Epi", "Γ ⊢ e : A → B", "Γ ⊢ u : B → T", "Γ ⊢ v : B → T", "Γ ⊢ ue = ve" },
                    new[] { "Γ ⊢ u = v", "Γ ⊢ [Epi] commutes" },
                    "Epimorphism cancellation — dually, e : Epi eliminates on the right: u∘e = v∘e forces u = v."),
                R("Structural", "mono-is-kernel",
                    new[] { "Γ ⊢ m : Mono", "Γ ⊢ m : K → A", "Γ ⊢ c : Coker m" },
                    new[] { "Γ ⊢ m : Ker c" },
                    "Abelian axiom: every monomorphism IS a kernel — precisely, m = ker(coker m): m is a kernel of its own cokernel c."),
                R("Structural", "epi-is-cokernel",
                    new[] { "Γ ⊢ e : Epi", "Γ ⊢ e : B → Q", "Γ ⊢ k : Ker e" },
                    new[] { "Γ ⊢ e : Coker k" },
                    "Abelian axiom, dually: every epimorphism is a cokernel — e = coker(ker e)."),
                R("Structural", "additive-functor",
                    new[] { "F : Additive" }, new[] { "F : Functor" },
                    "The class judgment F : Additive (F acts on hom-groups as a homomorphism) implies plain functoriality F : Functor. Both are rigid class markers, like Mono and Epi."),
                R("Computational", "functor-additive",
                    new[] { "F : C → D", "F : Additive", "Γ ⊢ f : A → B", "Γ ⊢ g : A → B", "Γ ⊢ s = f + g" },
                    new[] { "Γ ⊢ Fs = Ff + Fg" },
                    "An ADDITIVE functor F : C → D acts on hom-groups as a homomorphism: F(f + g) = Ff + Fg (Fx is F applied to x, by juxtaposition). The hypothesis F : Additive is essential — a plain functor need not satisfy this."),
                R("Computational", "functor-zero",
                    new[] { "F : C → D", "F : Additive" }, new[] { "F0 = 0" },
                    "Additive functors preserve zero morphisms (hence the zero object and biproducts). Again F : Additive is essential: the constant functor at Y sends 0 to 1ᵧ ≠ 0."),
                R("Computational", "functor-comp",
                    new[] { "F : C → D", "F : Functor", "Γ ⊢ f : A → B", "Γ ⊢ g : B → E" },
                    new[] { "Γ ⊢ Fgf = FgFf" },
                    "Functoriality: F(g∘f) = F(g)∘F(f) — read Fgf as F applied to the composite, FgFf as the composite of images. F : Functor keeps the rule from firing on an ordinary morphism that happens to be typed like a functor."),
            },
            new[]
            {
                ("Zero", "[0, 3, [0,0,\"X\"], [1,0,\"0\"], [2,0,\"Y\"], [0,1,\"t\"], [1,2,\"s\"], [0,2,\"0\",2,{\"curve\":2}]]"),
                ("Biprod", "[0, 3, [0,0,\"A\"], [1,0,\"A\\\\oplus B\"], [2,0,\"B\"], [0,1,\"i_1\",0,{\"curve\":-1}], [1,0,\"p_1\",0,{\"curve\":-1}], [2,1,\"i_2\",0,{\"curve\":-1}], [1,2,\"p_2\",0,{\"curve\":-1}]]"),
                ("Ker", "[0, 3, [0,0,\"K\"], [1,0,\"A\"], [2,0,\"B\"], [0,1,\"k\"], [1,2,\"f\"], [0,2,\"0\",2,{\"curve\":2}]]"),
                ("Coker", "[0, 3, [0,0,\"A\"], [1,0,\"B\"], [2,0,\"Q\"], [0,1,\"f\"], [1,2,\"c\"], [0,2,\"0\",2,{\"curve\":2}]]"),
                ("KerUniv", "[0, 4, [0,0,\"T\"], [0,1,\"K\"], [1,1,\"A\"], [2,1,\"B\"], [0,2,\"t\"], [0,1,\"u\",0,{\"style\":{\"body\":{\"name\":\"dashed\"}}}], [1,2,\"k\"], [2,3,\"f\"], [0,3,\"0\",2,{\"curve\":2}]]"),
                ("Mono", "[0, 3, [0,0,\"T\"], [1,0,\"A\"], [2,0,\"B\"], [0,1,\"u\",0,{\"curve\":-1}], [0,1,\"v\",0,{\"curve\":1}], [1,2,\"m\"]]"),
                ("Epi", "[0, 3, [0,0,\"A\"], [1,0,\"B\"], [2,0,\"T\"], [0,1,\"e\"], [1,2,\"u\",0,{\"curve\":-1}], [1,2,\"v\",0,{\"curve\":1}]]"),
            }),

        new("Pasting calculus",
            "The gluing lemma made concrete: two triangles I and J share the diagonal path K (the arrow d : A → D); pasting them along K yields the commutative square-with-diagonal IJ. Load it, prove [IJ] commutes on the Chase page from the two triangle facts, and read the boundary equation off the square.",
            new[]
            {
                R("Structural", "paste-glue",
                    new[] { "[I] commutes", "[J] commutes" }, new[] { "[IJ] commutes" },
                    "Gluing along the common path K (the diagonal d): any two parallel composites in IJ compare through d — via triangle I on the B-side, via triangle J on the C-side."),
                R("Structural", "subdiagram-I", new[] { "[IJ] commutes" }, new[] { "[I] commutes" },
                    "Restriction to the full subdiagram I: commutativity is inherited."),
                R("Structural", "subdiagram-J", new[] { "[IJ] commutes" }, new[] { "[J] commutes" },
                    "Restriction to the full subdiagram J: commutativity is inherited."),
                R("Structural", "K-commutes", None, new[] { "[K] commutes" },
                    "The shared path is a single arrow — it commutes vacuously (no parallel composites)."),
                R("Computational", "I-eq", new[] { "[I] commutes" }, new[] { "hf = d" },
                    "Triangle I says its two paths A → D agree: h∘f = d (juxtaposition is composition)."),
                R("Computational", "J-eq", new[] { "[J] commutes" }, new[] { "mk = d" },
                    "Triangle J says its two paths A → D agree: m∘k = d."),
                R("Computational", "IJ-eq", new[] { "hf = d", "mk = d" }, new[] { "hf = mk" },
                    "The boundary equation of the pasted square, by transitivity through the shared diagonal."),
            },
            new[]
            {
                ("I", "[0, 3, [0,0,\"A\"], [1,0,\"B\"], [1,1,\"D\"], [0,1,\"f\"], [1,2,\"h\"], [0,2,\"d\"]]"),
                ("J", "[0, 3, [0,0,\"A\"], [0,1,\"C\"], [1,1,\"D\"], [0,1,\"k\"], [1,2,\"m\"], [0,2,\"d\"]]"),
                ("K", "[0, 2, [0,0,\"A\"], [1,1,\"D\"], [0,1,\"d\"]]"),
                ("IJ", "[0, 4, [0,0,\"A\"], [1,0,\"B\"], [0,1,\"C\"], [1,1,\"D\"], [0,1,\"f\"], [1,3,\"h\"], [0,2,\"k\"], [2,3,\"m\"], [0,3,\"d\"]]"),
            }),

        new("Poset as a category",
            "The functor from posets to thin categories: elements are objects, x ≤ y is the unique arrow x → y. Reflexivity gives identities, transitivity gives composition, and thinness makes every diagram commute. (Antisymmetry corresponds to skeletality — mutually connected objects coincide — which lives outside the syntax as a side condition.)",
            new[]
            {
                R("Structural", "objects", None, new[] { "P : Type, x : P ⊢ x : P" },
                    "Each element of the poset is an object of the category."),
                R("Construction", "refl-id", None, new[] { "P : Type, x : P ⊢ idₓ : x → x" },
                    "Reflexivity x ≤ x becomes the identity arrow: hom(x, x) is inhabited."),
                R("Elimination", "trans-compose",
                    new[] { "Γ ⊢ f : x → y", "Γ ⊢ g : y → z" }, new[] { "Γ ⊢ gf : x → z" },
                    "Transitivity (x ≤ y and y ≤ z imply x ≤ z) becomes composition; gf stands for g ∘ f."),
                R("Computational", "thinness",
                    new[] { "Γ ⊢ f : x → y", "Γ ⊢ g : x → y" }, new[] { "Γ ⊢ [Par] commutes" },
                    "At most one arrow between any two objects: any parallel pair is equal, so every diagram in a poset-category commutes."),
                R("Structural", "point-commutes", None, new[] { "C : Type, X : C ⊢ [Pt] commutes" },
                    "A single-object diagram — no arrows, not even the identity drawn — commutes vacuously: there is no pair of parallel composites to compare."),
            },
            new[]
            {
                ("Pt", "[0, 1, [0,0,\"X\"]]"),
                ("Par", "[0, 2, [0,0,\"X\"], [1,0,\"Y\"], [0,1,\"f\"], [0,1,\"g\",2,{\"curve\":2}]]"),
            }),

        new("Linear logic (fragment)",
            "Resource-sensitive sequent calculus: × read as ⊗, + as ⊕, ∩ as & — multiplicative rules SPLIT the context (Γ, Δ), additive rules SHARE it; no weakening or contraction.",
            new[]
            {
                R("Structural", "axiom", None, new[] { "x : σ ⊢ x : σ" },
                    "Identity: exactly one hypothesis, used exactly once — the whole context is the single resource."),
                R("Introduction", "⊸-intro", new[] { "Γ, x : σ ⊢ M : τ" }, new[] { "Γ ⊢ λxM : σ → τ" },
                    "Linear abstraction: the body must use x exactly once."),
                R("Elimination", "⊸-elim", new[] { "Γ ⊢ f : σ → τ", "Δ ⊢ a : σ" }, new[] { "Γ, Δ ⊢ fa : τ" },
                    "Linear application — multiplicative: the function and argument consume disjoint resources Γ and Δ."),
                R("Introduction", "⊗-intro", new[] { "Γ ⊢ M : σ", "Δ ⊢ N : τ" }, new[] { "Γ, Δ ⊢ MN : σ × τ" },
                    "Tensor — multiplicative: the pair's components draw on disjoint contexts, both consumed."),
                R("Elimination", "⊗-elim", new[] { "Γ ⊢ p : σ × τ", "Δ, x : σ, y : τ ⊢ N : ρ" }, new[] { "Γ, Δ ⊢ M : ρ" },
                    "Tensor elimination: let (x, y) = p in N — both components must be used."),
                R("Introduction", "&-intro", new[] { "Γ ⊢ M : σ", "Γ ⊢ N : τ" }, new[] { "Γ ⊢ MN : σ ∩ τ" },
                    "With — additive: BOTH alternatives are offered from the SAME resources Γ; the consumer will pick one."),
                R("Elimination", "&-elim1", new[] { "Γ ⊢ p : σ ∩ τ" }, new[] { "Γ ⊢ p1 : σ" },
                    "Choose the left alternative."),
                R("Elimination", "&-elim2", new[] { "Γ ⊢ p : σ ∩ τ" }, new[] { "Γ ⊢ p2 : τ" },
                    "Choose the right alternative."),
                R("Introduction", "⊕-intro1", new[] { "Γ ⊢ M : σ" }, new[] { "Γ ⊢ M : σ + τ" },
                    "Left injection into the plus."),
                R("Introduction", "⊕-intro2", new[] { "Γ ⊢ M : τ" }, new[] { "Γ ⊢ M : σ + τ" },
                    "Right injection into the plus."),
                R("Elimination", "⊕-elim",
                    new[] { "Γ ⊢ M : σ + τ", "Δ, x : σ ⊢ N1 : ρ", "Δ, y : τ ⊢ N2 : ρ" }, new[] { "Γ, Δ ⊢ N : ρ" },
                    "Case analysis: whichever branch fires consumes Δ plus its injected component exactly once."),
            }),
    };
}
