namespace AbCatDC.RazorLib.Shared;

/// <summary>
/// Ready-made example palettes: small curated rule systems the user can load
/// into the rule editor as a starting point. Schematic where the kernel's
/// syntax lacks a native notion (noted in the descriptions).
/// </summary>
public static class ExampleSystems
{
    public record ExampleSystem(
        string Name, string Description, RulePalette.Entry[] Rules,
        (string Name, string Json)[]? Sketches = null,
        string[]? Constants = null);

    static RulePalette.Entry R(string kind, string name, string[] prem, string[] concl, string desc) =>
        new(kind, name, prem, concl, desc);

    static readonly string[] None = System.Array.Empty<string>();

    public static readonly ExampleSystem[] All =
    {
        new("Simply typed λ-calculus",
            "The minimal functional core in sequent style, with typing judgments t : T throughout.",
            new[]
            {
                R("Structural", "var", None, new[] { "Γ, x : σ ⊢ x : σ" },
                    "Variable rule: a hypothesis proves itself."),
                R("Introduction", "→-intro", new[] { "Γ, x : σ ⊢ M : τ" }, new[] { "Γ ⊢ λxM : σ → τ" },
                    "Abstraction: discharge the hypothesis x : σ; λxM stands for λx. M."),
                R("Elimination", "→-elim", new[] { "Γ ⊢ f : σ → τ", "Γ ⊢ a : σ" }, new[] { "Γ ⊢ fa : τ" },
                    "Application: fa stands for f a."),
                R("Computational", "β-compute", new[] { "Γ, x : σ ⊢ M : τ", "Γ ⊢ a : σ" }, new[] { "Γ ⊢ Mxa : τ" },
                    "β-reduction: (λx. M) a ↝ M[x := a]; Mxa stands for the substituted body."),
                R("Introduction", "×-intro", new[] { "Γ ⊢ M : σ", "Γ ⊢ N : τ" }, new[] { "Γ ⊢ MN : σ × τ" },
                    "Pairing: MN stands for the pair (M, N)."),
                R("Elimination", "×-proj1", new[] { "Γ ⊢ p : σ × τ" }, new[] { "Γ ⊢ p1 : σ" },
                    "First projection: p1 stands for π₁ p."),
                R("Elimination", "×-proj2", new[] { "Γ ⊢ p : σ × τ" }, new[] { "Γ ⊢ p2 : τ" },
                    "Second projection: p2 stands for π₂ p."),
            }),

        new("System F",
            "Girard/Reynolds polymorphism in sequent style with typing judgments.",
            new[]
            {
                R("Structural", "var", None, new[] { "Γ, x : σ ⊢ x : σ" }, "Variable rule."),
                R("Introduction", "→-intro", new[] { "Γ, x : σ ⊢ M : τ" }, new[] { "Γ ⊢ λxM : σ → τ" },
                    "Term abstraction, discharging x : σ."),
                R("Elimination", "→-elim", new[] { "Γ ⊢ f : σ → τ", "Γ ⊢ a : σ" }, new[] { "Γ ⊢ fa : τ" },
                    "Term application."),
                R("Introduction", "∀-intro", new[] { "Γ ⊢ M : τ" }, new[] { "Γ ⊢ M : ∀α. τ" },
                    "Type abstraction Λα. M — side condition: α not free in Γ."),
                R("Elimination", "∀-elim", new[] { "Γ ⊢ M : ∀α. τ" }, new[] { "Γ ⊢ M : τ" },
                    "Type application: the conclusion is at τ[α := σ] for any chosen σ."),
                R("Computational", "Λβ-compute", new[] { "Γ ⊢ M : ∀α. τ" }, new[] { "Γ ⊢ M : τ" },
                    "Type-level β: (Λα. M)[σ] ↝ M[α := σ]."),
                R("Introduction", "church-two", None, new[] { "⊢ c2 : ∀α. (α → α) → α → α" },
                    "A closed inhabitant: the Church numeral 2 = λf. λx. f (f x), typed in the empty context."),
            }),

        new("Martin-Löf type theory",
            "Dependent Π and Σ over ℕ with the induction principle.",
            new[]
            {
                R("Structural", "var", None, new[] { "Γ, x : σ ⊢ x : σ" }, "Variable rule."),
                R("Introduction", "Π-intro", new[] { "Γ, x : σ ⊢ M : τ" }, new[] { "Γ ⊢ λxM : (x : σ) → τ" },
                    "Dependent abstraction over the hypothesis x : σ."),
                R("Elimination", "Π-elim", new[] { "Γ ⊢ f : (x : σ) → τ", "Γ ⊢ a : σ" }, new[] { "Γ ⊢ fa : τ" },
                    "Dependent application: the result type is τ[x := a]."),
                R("Introduction", "Σ-intro", new[] { "Γ ⊢ a : σ", "Γ ⊢ b : τ" }, new[] { "Γ ⊢ ab : (x : σ) × τ" },
                    "Dependent pairing: witness a with proof b of τ[x := a]."),
                R("Elimination", "Σ-proj1", new[] { "Γ ⊢ p : (x : σ) × τ" }, new[] { "Γ ⊢ p1 : σ" },
                    "First projection: the witness."),
                R("Elimination", "Σ-proj2", new[] { "Γ ⊢ p : (x : σ) × τ" }, new[] { "Γ ⊢ p2 : τ" },
                    "Second projection, at type τ[x := π₁ p]."),
                R("Construction", "ℕ-zero", None, new[] { "⊢ 0 : ℕ" }, "Zero, in the empty context."),
                R("Construction", "ℕ-succ", new[] { "Γ ⊢ n : ℕ" }, new[] { "Γ ⊢ n + 1 : ℕ" }, "Successor."),
                R("Elimination", "ℕ-ind",
                    new[] { "Γ ⊢ z : ρ", "Γ ⊢ s : (n : ℕ) → ρ → ρ", "Γ ⊢ m : ℕ" }, new[] { "Γ ⊢ r : ρ" },
                    "Induction / recursion: r stands for ind(z, s, m) — base case z, step s, applied to m."),
            }),

        new("Cubical type theory",
            "Schematic cubical primitives: the interval I, paths as functions out of it, transport and composition.",
            new[]
            {
                R("Construction", "I-0", None, new[] { "0" },
                    "The left endpoint of the interval I (rendered as the numeral 0)."),
                R("Construction", "I-1", None, new[] { "1" },
                    "The right endpoint of the interval I."),
                R("Introduction", "Path-intro", new[] { "τ" }, new[] { "(i : I) → τ" },
                    "A path is a function out of the interval: λi. M, with M possibly mentioning i."),
                R("Elimination", "Path-app", new[] { "(i : I) → τ", "I" }, new[] { "τ" },
                    "Evaluate a path at an interval point; the endpoints give the two sides of the equality."),
                R("Construction", "refl", new[] { "σ" }, new[] { "(i : I) → σ" },
                    "The constant path at a point — reflexivity."),
                R("Computational", "transp", new[] { "(i : I) → τ" }, new[] { "τ → τ" },
                    "Transport along a line of types: coerce the fiber at 0 into the fiber at 1."),
                R("Computational", "hcomp", new[] { "σ", "(i : I) → σ" }, new[] { "σ" },
                    "Homogeneous composition: cap an open box in σ."),
                R("Computational", "funext", new[] { "(x : σ) → (i : I) → τ" }, new[] { "(i : I) → (x : σ) → τ" },
                    "Function extensionality: a family of paths swaps into a path of functions."),
                R("Computational", "conn-meet", new[] { "I", "I" }, new[] { "I" },
                    "Connection i ∧ j: the meet operation on the interval."),
                R("Computational", "conn-join", new[] { "I", "I" }, new[] { "I" },
                    "Connection i ∨ j: the join operation on the interval."),
                R("Computational", "ua", new[] { "σ → τ", "τ → σ" }, new[] { "(i : I) → σ ∪ τ" },
                    "Univalence, schematically: an equivalence between σ and τ yields a line of types between them."),
            }),

        new("Peano arithmetic",
            "ℤ-flavored arithmetic: zero, successor, the defining equations of addition, and induction.",
            new[]
            {
                R("Construction", "zero", None, new[] { "0" }, "The numeral 0 : ℕ."),
                R("Construction", "succ", new[] { "n" }, new[] { "n + 1" },
                    "Successor: n ↦ n + 1, computing in ℤ."),
                R("Computational", "add-zero", new[] { "n + 0" }, new[] { "n" },
                    "Defining equation: n + 0 = n."),
                R("Computational", "add-succ", new[] { "n + (m + 1)" }, new[] { "(n + m) + 1" },
                    "Defining equation: n + s(m) = s(n + m)."),
                R("Computational", "ℤ-add-2+2", new[] { "2 + 2" }, new[] { "4" },
                    "A closed instance: 2 + 2 computes to 4 in ℤ."),
                R("Elimination", "ℕ-ind", new[] { "ρ", "(n : ℕ) → ρ → ρ", "ℕ" }, new[] { "ρ" },
                    "Induction: ρ(0) and ∀n. ρ(n) → ρ(n+1) give ρ for every natural number."),
            }),

        new("Intersection types",
            "The intersection type discipline — the system whose typable terms are exactly the strongly normalizing ones.",
            new[]
            {
                R("Introduction", "∩-intro", new[] { "σ", "τ" }, new[] { "σ ∩ τ" },
                    "One and the same term must inhabit both types."),
                R("Elimination", "∩-elim1", new[] { "σ ∩ τ" }, new[] { "σ" }, "Left component."),
                R("Elimination", "∩-elim2", new[] { "σ ∩ τ" }, new[] { "τ" }, "Right component."),
                R("Computational", "∩-idem", new[] { "σ ∩ σ" }, new[] { "σ" }, "Idempotence."),
                R("Computational", "∩-comm", new[] { "σ ∩ τ" }, new[] { "τ ∩ σ" }, "Commutativity."),
                R("Elimination", "∩-mono", new[] { "A → B" }, new[] { "(A ∩ X) → (B ∩ X)" },
                    "Monotonicity of intersection in a subtyping reading."),
                R("Elimination", "→-elim", new[] { "σ → τ", "σ" }, new[] { "τ" }, "Application."),
            }),

        new("Abelian categories",
            "The definitional tower of an abelian category, as diagrammatically as the language allows: hom-sets are abelian groups (composition bilinear), there is a zero object [Zero], every pair has a biproduct [Biprod], every morphism has a kernel [Ker] and cokernel [Coker] with their universal properties [KerUniv], and the abelian axioms make every mono a kernel and every epi a cokernel. Additive functors preserve the structure. (The remaining axiom — the canonical map coim f → im f is an isomorphism — needs image factorizations and is stated here only as this note.)",
            new[]
            {
                R("Construction", "hom-add",
                    new[] { "Γ ⊢ f : A → B", "Γ ⊢ g : A → B" }, new[] { "Γ ⊢ f + g : A → B" },
                    "Ab-enrichment: parallel morphisms add — hom(A, B) is an abelian group."),
                R("Construction", "hom-zero", None,
                    new[] { "C : Type, A : C, B : C ⊢ 0 : A → B" },
                    "Every hom-group has its zero element: the zero morphism, written literally 0."),
                R("Construction", "hom-neg",
                    new[] { "Γ ⊢ f : A → B" }, new[] { "Γ ⊢ ⋃(g:A → B) (g + f = 0)" },
                    "Additive inverses: for every f there exists g (= −f) with g + f = 0."),
                R("Computational", "comp-bilinear",
                    new[] { "Γ ⊢ h : B → D", "Γ ⊢ f : A → B", "Γ ⊢ g : A → B", "Γ ⊢ s = f + g" },
                    new[] { "Γ ⊢ hs = hf + hg" },
                    "Composition is bilinear over addition, left law: h∘(f + g) = h∘f + h∘g (juxtaposition is composition). The typings keep f, g, s in the hom-set composable with h."),
                R("Computational", "comp-bilinear-r",
                    new[] { "Γ ⊢ e : E → A", "Γ ⊢ f : A → B", "Γ ⊢ g : A → B", "Γ ⊢ s = f + g" },
                    new[] { "Γ ⊢ se = fe + ge" },
                    "Bilinearity, right law: (f + g)∘e = f∘e + g∘e."),
                R("Structural", "zero-object", None,
                    new[] { "C : Type, X : C, Y : C ⊢ [Zero] commutes" },
                    "There is a zero object 0, initial and terminal: t : X → 0 and s : 0 → Y are the unique such maps, and the diagram commuting says the zero morphism X → Y is exactly s∘t."),
                R("Construction", "biproduct", None,
                    new[] { "C : Type, A : C, B : C ⊢ [Biprod] in C",
                            "C : Type, A : C, B : C ⊢ i₁ : A → S",
                            "C : Type, A : C, B : C ⊢ i₂ : B → S",
                            "C : Type, A : C, B : C ⊢ p₁ : S → A",
                            "C : Type, A : C, B : C ⊢ p₂ : S → B",
                            "C : Type, A : C, B : C ⊢ p₁i₁ = 1ₐ",
                            "C : Type, A : C, B : C ⊢ p₂i₂ = 1ᵦ",
                            "C : Type, A : C, B : C ⊢ i₁p₁ + i₂p₂ = 1ₛ" },
                    "Every pair has a biproduct A ⊕ B, here introduced as the fresh object S with injections i₁, i₂ and projections p₁, p₂ satisfying p₁i₁ = 1ₐ, p₂i₂ = 1ᵦ, and the characteristic identity i₁p₁ + i₂p₂ = 1ₛ — product and coproduct at once, courtesy of the additive structure. (1ₓ names are rigid identity notation.)"),
                R("Construction", "kernel",
                    new[] { "Γ ⊢ f : A → B" },
                    new[] { "Γ ⊢ k : Ker f", "Γ ⊢ k : K → A", "Γ ⊢ fk = 0", "Γ ⊢ [Ker] commutes" },
                    "Every morphism has a kernel: k : K → A with f∘k = 0. The judgment k : Ker f is the marker 'k is a kernel of f' — it is what licenses the universal property below."),
                R("Elimination", "kernel-universal",
                    new[] { "Γ ⊢ k : Ker f", "Γ ⊢ f : A → B", "Γ ⊢ k : K → A", "Γ ⊢ t : T → A", "Γ ⊢ ft = 0" },
                    new[] { "Γ ⊢ ⋃(u:T → K) (ku = t)", "Γ ⊢ [KerUniv] commutes" },
                    "The kernel's universal property: any t with f∘t = 0 factors uniquely through K — the dashed u in the diagram, with k∘u = t. Note the hypothesis k : Ker f — without it, this would let t factor through an arbitrary k."),
                R("Construction", "cokernel",
                    new[] { "Γ ⊢ f : A → B" },
                    new[] { "Γ ⊢ c : Coker f", "Γ ⊢ c : B → Q", "Γ ⊢ cf = 0", "Γ ⊢ [Coker] commutes" },
                    "Dually, every morphism has a cokernel: c : B → Q with c∘f = 0, marked by c : Coker f."),
                R("Structural", "ker-mono",
                    new[] { "Γ ⊢ k : Ker f" }, new[] { "Γ ⊢ k : Mono" },
                    "Kernels are monic — the introduction rule for the class judgment Mono: if k∘u = k∘v then f∘(ku) = 0 = f∘(kv), and both factor uniquely through k, so u = v."),
                R("Structural", "coker-epi",
                    new[] { "Γ ⊢ c : Coker f" }, new[] { "Γ ⊢ c : Epi" },
                    "Cokernels are epic — dually, the introduction rule for Epi."),
                R("Elimination", "mono-cancel",
                    new[] { "Γ ⊢ m : Mono", "Γ ⊢ m : A → B", "Γ ⊢ u : T → A", "Γ ⊢ v : T → A", "Γ ⊢ mu = mv" },
                    new[] { "Γ ⊢ u = v", "Γ ⊢ [Mono] commutes" },
                    "Monomorphism cancellation — the elimination rule for the class judgment m : Mono: given m∘u = m∘v the parallel pair collapses to u = v, which is exactly what [Mono] commuting asserts. Being mono MEANS admitting this rule."),
                R("Elimination", "epi-cancel",
                    new[] { "Γ ⊢ e : Epi", "Γ ⊢ e : A → B", "Γ ⊢ u : B → T", "Γ ⊢ v : B → T", "Γ ⊢ ue = ve" },
                    new[] { "Γ ⊢ u = v", "Γ ⊢ [Epi] commutes" },
                    "Epimorphism cancellation — dually, e : Epi eliminates on the right: u∘e = v∘e forces u = v."),
                R("Structural", "mono-is-kernel",
                    new[] { "Γ ⊢ m : Mono", "Γ ⊢ m : K → A", "Γ ⊢ c : Coker m" },
                    new[] { "Γ ⊢ m : Ker c" },
                    "Abelian axiom: every monomorphism IS a kernel — precisely, m = ker(coker m): m is a kernel of its own cokernel c."),
                R("Structural", "epi-is-cokernel",
                    new[] { "Γ ⊢ e : Epi", "Γ ⊢ e : B → Q", "Γ ⊢ k : Ker e" },
                    new[] { "Γ ⊢ e : Coker k" },
                    "Abelian axiom, dually: every epimorphism is a cokernel — e = coker(ker e)."),
                R("Structural", "additive-functor",
                    new[] { "F : Additive" }, new[] { "F : Functor" },
                    "The class judgment F : Additive (F acts on hom-groups as a homomorphism) implies plain functoriality F : Functor. Both are rigid class markers, like Mono and Epi."),
                R("Computational", "functor-additive",
                    new[] { "F : C → D", "F : Additive", "Γ ⊢ f : A → B", "Γ ⊢ g : A → B", "Γ ⊢ s = f + g" },
                    new[] { "Γ ⊢ Fs = Ff + Fg" },
                    "An ADDITIVE functor F : C → D acts on hom-groups as a homomorphism: F(f + g) = Ff + Fg (Fx is F applied to x, by juxtaposition). The hypothesis F : Additive is essential — a plain functor need not satisfy this."),
                R("Computational", "functor-zero",
                    new[] { "F : C → D", "F : Additive" }, new[] { "F0 = 0" },
                    "Additive functors preserve zero morphisms (hence the zero object and biproducts). Again F : Additive is essential: the constant functor at Y sends 0 to 1ᵧ ≠ 0."),
                R("Computational", "functor-comp",
                    new[] { "F : C → D", "F : Functor", "Γ ⊢ f : A → B", "Γ ⊢ g : B → E" },
                    new[] { "Γ ⊢ Fgf = FgFf" },
                    "Functoriality: F(g∘f) = F(g)∘F(f) — read Fgf as F applied to the composite, FgFf as the composite of images. F : Functor keeps the rule from firing on an ordinary morphism that happens to be typed like a functor."),
            },
            new[]
            {
                ("Zero", "[0, 3, [0,0,\"X\"], [1,0,\"0\"], [2,0,\"Y\"], [0,1,\"!t\",0,{\"style\":{\"body\":{\"name\":\"dashed\"}}}], [1,2,\"!s\",0,{\"style\":{\"body\":{\"name\":\"dashed\"}}}], [0,2,\"0\",2,{\"curve\":2}]]"),
                ("Biprod", "[0, 3, [0,0,\"A\"], [1,0,\"S\"], [2,0,\"B\"], [0,1,\"i_1\",0,{\"curve\":-1}], [1,0,\"p_1\",0,{\"curve\":-1}], [2,1,\"i_2\",0,{\"curve\":-1}], [1,2,\"p_2\",0,{\"curve\":-1}]]"),
                ("Ker", "[0, 3, [0,0,\"K\"], [1,0,\"A\"], [2,0,\"B\"], [0,1,\"k\"], [1,2,\"f\"], [0,2,\"0\",2,{\"curve\":2}]]"),
                ("Coker", "[0, 3, [0,0,\"A\"], [1,0,\"B\"], [2,0,\"Q\"], [0,1,\"f\"], [1,2,\"c\"], [0,2,\"0\",2,{\"curve\":2}]]"),
                ("KerUniv", "[0, 4, [0,0,\"T\"], [0,1,\"K\"], [1,1,\"A\"], [2,1,\"B\"], [0,2,\"t\"], [0,1,\"!u\",0,{\"style\":{\"body\":{\"name\":\"dashed\"}}}], [1,2,\"k\"], [2,3,\"f\"], [0,3,\"0\",2,{\"curve\":2}]]"),
                ("Mono", "[0, 3, [0,0,\"T\"], [1,0,\"A\"], [2,0,\"B\"], [0,1,\"u\",0,{\"curve\":-1}], [0,1,\"v\",0,{\"curve\":1}], [1,2,\"m\"]]"),
                ("Epi", "[0, 3, [0,0,\"A\"], [1,0,\"B\"], [2,0,\"T\"], [0,1,\"e\"], [1,2,\"u\",0,{\"curve\":-1}], [1,2,\"v\",0,{\"curve\":1}]]"),
            }),

        new("Pasting calculus",
            "The gluing lemma made concrete: two triangles I and J share the diagonal path K (the arrow d : A → D); pasting them along K yields the commutative square-with-diagonal IJ. Load it, prove [IJ] commutes on the Chase page from the two triangle facts, and read the boundary equation off the square.",
            new[]
            {
                R("Structural", "paste-glue",
                    new[] { "[I] commutes", "[J] commutes" }, new[] { "[IJ] commutes" },
                    "Gluing along the common path K (the diagonal d): any two parallel composites in IJ compare through d — via triangle I on the B-side, via triangle J on the C-side."),
                R("Structural", "subdiagram-I", new[] { "[IJ] commutes" }, new[] { "[I] commutes" },
                    "Restriction to the full subdiagram I: commutativity is inherited."),
                R("Structural", "subdiagram-J", new[] { "[IJ] commutes" }, new[] { "[J] commutes" },
                    "Restriction to the full subdiagram J: commutativity is inherited."),
                R("Structural", "K-commutes", new[] { "d : A → D" }, new[] { "[K] commutes" },
                    "The shared path is a single arrow — it commutes vacuously (no parallel composites). The premise binds the arrow the picture shows, so the rule instantiates to whichever arrow you give it."),
                R("Computational", "I-eq", new[] { "[I] commutes" }, new[] { "hf = d" },
                    "Triangle I says its two paths A → D agree: h∘f = d (juxtaposition is composition)."),
                R("Computational", "J-eq", new[] { "[J] commutes" }, new[] { "mk = d" },
                    "Triangle J says its two paths A → D agree: m∘k = d."),
                R("Computational", "IJ-eq", new[] { "hf = d", "mk = d" }, new[] { "hf = mk" },
                    "The boundary equation of the pasted square, by transitivity through the shared diagonal."),
            },
            new[]
            {
                ("I", "[0, 3, [0,0,\"A\"], [1,0,\"B\"], [1,1,\"D\"], [0,1,\"f\"], [1,2,\"h\"], [0,2,\"d\"]]"),
                ("J", "[0, 3, [0,0,\"A\"], [0,1,\"C\"], [1,1,\"D\"], [0,1,\"k\"], [1,2,\"m\"], [0,2,\"d\"]]"),
                ("K", "[0, 2, [0,0,\"A\"], [1,1,\"D\"], [0,1,\"d\"]]"),
                ("IJ", "[0, 4, [0,0,\"A\"], [1,0,\"B\"], [0,1,\"C\"], [1,1,\"D\"], [0,1,\"f\"], [1,3,\"h\"], [0,2,\"k\"], [2,3,\"m\"], [0,3,\"d\"]]"),
            }),

        new("Generic objects",
            "What it MEANS to write A : C for C : category — the object layer, spelled out. Here category is the universe of categories, C : category says C is a category, and A : C says A is an object OF C. Both category and id are declared rigid constants, so no rule can ever instantiate them as metavariables, and id is function-like: id A is the identity morphism on A.",
            new[]
            {
                R("Structural", "category-formation", None, new[] { "category : Type" },
                    "The universe: category is itself a type, so C : category is a well-formed judgment. Declared rigid, so it is a fixed constant rather than a schematic name."),
                R("Structural", "object-hyp", None, new[] { "C : category, A : C ⊢ A : C" },
                    "The variable (assumption) rule for objects: having assumed C is a category and A an object of it, A IS an object of it. This one genuinely has no premises — it is the axiom that BOTTOMS OUT the object layer, and lifting its hypotheses above the line would make it circular (it would need Γ ⊢ A : C to conclude Γ ⊢ A : C). Every other rule of this palette instead takes its hypotheses as premises."),
                R("Construction", "hom-formation",
                    new[] { "Γ ⊢ C : category", "Γ ⊢ A : C", "Γ ⊢ B : C" },
                    new[] { "Γ ⊢ A → B : Type" },
                    "Hom-formation: any two objects of the same category span a type of morphisms A → B. Both A and B are checked against the SAME C — an arrow never crosses categories. Premises above the line, so the rule fires on objects already established in the proof."),
                R("Construction", "identity",
                    new[] { "Γ ⊢ C : category", "Γ ⊢ A : C" },
                    new[] { "Γ ⊢ id A : A → A" },
                    "Every object carries an identity morphism — given that C is a category and A is one of its objects. Stated with the hypotheses ABOVE the line (rather than inside one fixed context) so the rule applies in whatever context a proof is already using, instantiating C and A from steps already proved. Because id is function-like, id A tracks the object A schematically — unlike the fixed notation 1ₐ, which names one particular identity."),
                R("Elimination", "codomain-object",
                    new[] { "Γ ⊢ C : category", "Γ ⊢ m : A → B", "Γ ⊢ A : C" },
                    new[] { "Γ ⊢ B : C" },
                    "Objects are closed under being the target of an arrow: if m : A → B lives in C and A is an object of C, so is B."),
                R("Computational", "object-cong", new[] { "Γ ⊢ A = B" }, new[] { "Γ ⊢ id A = id B" },
                    "Congruence for the object layer: equal objects have equal identities. Equality is symmetric in the kernel, so this fires in either orientation."),
            },
            null,
            new[] { "category", "id" }),

        new("Generic morphisms",
            "What it MEANS to write m : A → B — the morphism layer. A hom-typing is a hypothesis like any other; juxtaposition is composition (gm is g∘m, RIGHTMOST APPLIED FIRST); identities are units for it; and composition is associative and congruent. Because composites are written as juxtaposed names, the unit and associativity laws name their composites in premises (e = id A, p = hg) instead of nesting parentheses.",
            new[]
            {
                R("Structural", "hom-hyp", None,
                    new[] { "C : category, A : C, B : C, m : A → B ⊢ m : A → B" },
                    "The variable rule for morphisms, and the definition of the notation: m : A → B assumes m is an arrow with domain A and codomain B, both objects of the ambient category C. Like object-hyp this is an axiom with nothing above the line — assuming a hom-typing is what makes it available; there is nothing prior to derive it from. Everything else about m comes from rules, never from its name."),
                R("Construction", "compose",
                    new[] { "Γ ⊢ m : A → B", "Γ ⊢ g : B → D" }, new[] { "Γ ⊢ gm : A → D" },
                    "Composition: the codomain of m must match the domain of g, and the composite is written by juxtaposition, gm = g∘m. Read right to left — m applies first."),
                R("Computational", "id-left",
                    new[] { "Γ ⊢ m : A → B", "Γ ⊢ e : B → B", "Γ ⊢ e = id B" },
                    new[] { "Γ ⊢ em = m" },
                    "Left unit law: the identity on the codomain composes away. The identity is named e by a premise so that em is a juxtaposition of two names — (id B)m is not writable in this notation."),
                R("Computational", "id-right",
                    new[] { "Γ ⊢ m : A → B", "Γ ⊢ e : A → A", "Γ ⊢ e = id A" },
                    new[] { "Γ ⊢ me = m" },
                    "Right unit law, dually: the identity on the domain composes away."),
                R("Computational", "assoc",
                    new[] { "Γ ⊢ p = hg", "Γ ⊢ q = gm" }, new[] { "Γ ⊢ pm = hq" },
                    "Associativity: naming the inner composites p = h∘g and q = g∘m, the law reads (h∘g)∘m = h∘(g∘m). Flat juxtaposition hgm is already unambiguous — this rule is what licenses that."),
                R("Computational", "comp-cong-left",
                    new[] { "Γ ⊢ m = n", "Γ ⊢ m : A → B", "Γ ⊢ n : A → B", "Γ ⊢ g : B → D" },
                    new[] { "Γ ⊢ gm = gn" },
                    "Congruence in the right argument: equal morphisms stay equal after post-composition."),
                R("Computational", "comp-cong-right",
                    new[] { "Γ ⊢ g = h", "Γ ⊢ g : B → D", "Γ ⊢ h : B → D", "Γ ⊢ m : A → B" },
                    new[] { "Γ ⊢ gm = hm" },
                    "Congruence in the left argument: equal morphisms stay equal after pre-composition."),
            },
            null,
            new[] { "category", "id" }),

        new("Objects and hom-types",
            "Ob(C) and Hom(C, X, Y) as first-class types. Ob and Hom are declared rigid constants applied to their arguments, so both are parameterized by the category rather than freezing one into the name. Ob-intro/Ob-elim make X : C and X : Ob(C) interderivable, and Hom-fold/Hom-unfold do the same for f : X → Y and f : Hom(C, X, Y) — an interderivability pair IS how this system expresses an equivalence of notations, since it has no primitive notion of definitional equality between judgments. Parenthesized argument lists are input sugar: Hom(C, X, Y) and Hom C X Y are the same term, and the formatter prints the second.",
            new[]
            {
                R("Construction", "Ob-formation",
                    new[] { "Γ ⊢ C : category" }, new[] { "Γ ⊢ Ob(C) : Type" },
                    "Every category has a type of objects. Ob is function-like, so Ob(C) tracks whichever category C is — it is one constant, not a family of unrelated names."),
                R("Structural", "Ob-intro",
                    new[] { "Γ ⊢ C : category", "Γ ⊢ X : C" }, new[] { "Γ ⊢ X : Ob(C)" },
                    "The shorthand X : C (typing an object directly by its category) unfolds into the explicit X : Ob(C). Half of the equivalence between the two notations."),
                R("Structural", "Ob-elim",
                    new[] { "Γ ⊢ C : category", "Γ ⊢ X : Ob(C)" }, new[] { "Γ ⊢ X : C" },
                    "The converse: an inhabitant of Ob(C) is an object of C. With Ob-intro this makes the two spellings interderivable, so a proof may move freely between them."),
                R("Construction", "Hom-formation",
                    new[] { "Γ ⊢ C : category", "Γ ⊢ X : Ob(C)", "Γ ⊢ Y : Ob(C)" },
                    new[] { "Γ ⊢ Hom(C, X, Y) : Type" },
                    "Two objects of the same category span a hom-type. Both X and Y are checked against the SAME Ob(C), which is what stops a hom-type from straddling two categories."),
                R("Introduction", "Hom-fold",
                    new[] { "Γ ⊢ X : Ob(C)", "Γ ⊢ Y : Ob(C)", "Γ ⊢ f : X → Y" },
                    new[] { "Γ ⊢ f : Hom(C, X, Y)" },
                    "An arrow f : X → Y between objects of C IS an element of the hom-type. The premises X : Ob(C), Y : Ob(C) are what supply the category — an arrow judgment alone does not say which category it lives in."),
                R("Elimination", "Hom-unfold",
                    new[] { "Γ ⊢ X : Ob(C)", "Γ ⊢ Y : Ob(C)", "Γ ⊢ f : Hom(C, X, Y)" },
                    new[] { "Γ ⊢ f : X → Y" },
                    "The converse: an element of the hom-type is an arrow. Hom-fold and Hom-unfold together give exactly the equivalence f : X → Y iff f : Hom(C, X, Y), in any context where X and Y are objects of C."),
                R("Construction", "Hom-id",
                    new[] { "Γ ⊢ X : Ob(C)" }, new[] { "Γ ⊢ id X : Hom(C, X, X)" },
                    "Every hom-type at a repeated object is inhabited by the identity."),
                R("Construction", "Hom-compose",
                    new[] { "Γ ⊢ f : Hom(C, X, Y)", "Γ ⊢ g : Hom(C, Y, Z)" },
                    new[] { "Γ ⊢ gf : Hom(C, X, Z)" },
                    "Composition stated on hom-types: matching the middle object Y is forced by the two premises, so no separate side condition is needed."),
            },
            null,
            new[] { "category", "Ob", "Hom", "id" }),

        new("Concrete categories",
            "When is f : A → B actually FUNCTION-like? Only when the ambient category is concrete — that is, when its objects carry underlying sets. Concreteness is asserted by the rigid marker C : concrete, and it is that marker which unlocks the application rule: given f : Hom(C, A, B) and an element x : U(C, A) you may form fx : U(C, B). Take the marker away and NO rule lets you apply f to anything, so → degenerates to the bare abstract arrow of a general category — the notation is unchanged, the available rules are what differ. U is the underlying-set (forgetful) functor, written U(C, A) on objects and U(C, f) on morphisms; the honestly function-typed arrow is the one between underlying sets, U(C, A) → U(C, B), while Hom(C, A, B) stays abstract.",
            new[]
            {
                R("Structural", "concrete-is-category",
                    new[] { "Γ ⊢ C : concrete" }, new[] { "Γ ⊢ C : category" },
                    "Concreteness is extra structure on a category, not a rival notion: every concrete category is a category, so every rule of the generic palettes still applies to it. The converse is deliberately absent — that asymmetry is the whole point."),
                R("Construction", "underlying-object",
                    new[] { "Γ ⊢ C : concrete", "Γ ⊢ A : Ob(C)" }, new[] { "Γ ⊢ U(C, A) : Set" },
                    "Each object of a concrete category has an underlying set U(C, A). In a general category there is no such rule, so its objects have no elements to speak of."),
                R("Construction", "underlying-morphism",
                    new[] { "Γ ⊢ C : concrete", "Γ ⊢ f : Hom(C, A, B)" },
                    new[] { "Γ ⊢ U(C, f) : U(C, A) → U(C, B)" },
                    "Each morphism has an underlying FUNCTION between those sets. Note the two different arrows in play: Hom(C, A, B) is the abstract arrow of C, while U(C, A) → U(C, B) is a genuine function type — this rule is the bridge between them."),
                R("Elimination", "apply",
                    new[] { "Γ ⊢ C : concrete", "Γ ⊢ f : Hom(C, A, B)", "Γ ⊢ x : U(C, A)" },
                    new[] { "Γ ⊢ fx : U(C, B)" },
                    "THE function-like rule: apply f to an element. Juxtaposition fx is application here, exactly as it is composition on morphisms. This rule REQUIRES the concrete marker, which is precisely what makes f function-like — in a general category it is unavailable and f cannot be applied to anything."),
                R("Computational", "apply-id",
                    new[] { "Γ ⊢ e = id A", "Γ ⊢ x : U(C, A)" }, new[] { "Γ ⊢ ex = x" },
                    "The identity acts as the identity function on elements. The identity is named e by a premise so that ex is a juxtaposition of two names."),
                R("Computational", "apply-comp",
                    new[] { "Γ ⊢ h = gf", "Γ ⊢ x : U(C, A)", "Γ ⊢ y = fx" }, new[] { "Γ ⊢ hx = gy" },
                    "Composition acts by applying in order: (g∘f)(x) = g(f(x)). The inner application is named y by a premise, since the notation writes application by juxtaposition and cannot nest parentheses."),
                R("Structural", "faithful",
                    new[] { "Γ ⊢ C : concrete", "Γ ⊢ f : Hom(C, A, B)", "Γ ⊢ g : Hom(C, A, B)",
                            "Γ, x : U(C, A) ⊢ fx = gx" },
                    new[] { "Γ ⊢ f = g" },
                    "Faithfulness — extensionality for morphisms: two parallel morphisms that agree on every element are EQUAL. This is the real content of concreteness, and it fails badly in a general category, where distinct morphisms need not be distinguishable by anything element-like."),
                R("Introduction", "injective-intro",
                    new[] { "Γ, x : U(C, A), y : U(C, A), mx = my ⊢ x = y" },
                    new[] { "Γ ⊢ m : injective C" },
                    "What it takes to prove m INJECTIVE, in natural-deduction style: work in a context extended with two arbitrary elements x, y and the ASSUMPTION mx = my, and derive x = y. Since x and y are hypotheses of the premise and appear nowhere in the conclusion, they are automatically arbitrary — that discharge is what the quantifiers used to say. Compare the equivalent one-liner ⋂(x:U(C, A)) ⋂(y:U(C, A)) ((mx = my) → (x = y)), which states the same thing but has to be proved as a single closed formula."),
                R("Elimination", "injective-elim",
                    new[] { "Γ ⊢ m : injective C", "Γ ⊢ x : U(C, A)", "Γ ⊢ y : U(C, A)", "Γ ⊢ mx = my" },
                    new[] { "Γ ⊢ x = y" },
                    "What being injective BUYS you: any two elements with the same image are equal. Intro and elim together define the marker — nothing else may produce or consume m : injective C."),
                R("Introduction", "injective-mono",
                    new[] { "Γ ⊢ C : concrete", "Γ ⊢ m : Hom(C, A, B)", "Γ ⊢ m : injective C" },
                    new[] { "Γ ⊢ m : monomorphism C" },
                    "The payoff: in a concrete category an injective morphism is monic — the elementwise condition implies the cancellation condition. In a general category injectivity is not even expressible, and mono must be proved by cancellation directly (see the Rules for monomorphisms palette)."),
            },
            null,
            new[] { "category", "concrete", "Ob", "Hom", "U", "Set", "id", "monomorphism", "injective" }),

        new("Rules for monomorphisms",
            "A complete definition of m : monomorphism C — m is a monomorphism in the category C — with no diagrams at all. monomorphism is a rigid constant APPLIED to the ambient category, so the judgment is parameterized by C rather than baking one category into the name. The intro rule states left-cancellability as a typed universal (⋂ is the typed forall); the elimination rule is the one the prover actually fires; the rest are the standard closure properties. Load Generic objects and Generic morphisms alongside for the layers underneath.",
            new[]
            {
                R("Introduction", "mono-intro",
                    new[] { "Γ ⊢ C : category", "Γ ⊢ m : A → B",
                            "Γ, T : C, u : T → A, v : T → A, mu = mv ⊢ u = v" },
                    new[] { "Γ ⊢ m : monomorphism C" },
                    "THE DEFINITION, in natural-deduction style: to prove m monic, work in a context extended with an arbitrary test object T, an arbitrary parallel pair u, v into the domain, and the ASSUMPTION mu = mv — then derive u = v. T, u and v are hypotheses of the premise and occur nowhere in the conclusion, so they are automatically arbitrary; that discharge is what a universal quantifier would otherwise have to say. The equivalent closed formula is ⋂(T:C) ⋂(u:T → A) ⋂(v:T → A) ((mu = mv) → (u = v)), which means the same but must be proved in one piece."),
                R("Elimination", "mono-cancel",
                    new[] { "Γ ⊢ m : monomorphism C", "Γ ⊢ m : A → B", "Γ ⊢ u : T → A", "Γ ⊢ v : T → A", "Γ ⊢ mu = mv" },
                    new[] { "Γ ⊢ u = v" },
                    "Left cancellation — the rule that does the work in a proof, and the operational content of being monic: from m∘u = m∘v conclude u = v. Note the marker premise: WITHOUT m : monomorphism C this rule would collapse every parallel pair and the system would be unsound."),
                R("Structural", "mono-id",
                    new[] { "Γ ⊢ e : A → A", "Γ ⊢ e = id A" }, new[] { "Γ ⊢ e : monomorphism C" },
                    "Identities are monic: id A ∘ u = id A ∘ v is already u = v, by the unit law."),
                R("Construction", "mono-comp",
                    new[] { "Γ ⊢ m : monomorphism C", "Γ ⊢ n : monomorphism C", "Γ ⊢ m : B → D", "Γ ⊢ n : A → B" },
                    new[] { "Γ ⊢ mn : monomorphism C" },
                    "Monos compose: cancelling m and then n cancels the composite mn. With mono-id this makes the monomorphisms of C a subcategory containing every object."),
                R("Elimination", "mono-left-factor",
                    new[] { "Γ ⊢ p : monomorphism C", "Γ ⊢ p = mn", "Γ ⊢ n : A → B", "Γ ⊢ m : B → D" },
                    new[] { "Γ ⊢ n : monomorphism C" },
                    "The right-hand factor of a mono is mono: if m∘n is left-cancellable then so is n, since n∘u = n∘v gives m∘n∘u = m∘n∘v and then cancels. The other factor m need NOT be monic — that asymmetry is the useful half."),
                R("Structural", "mono-split",
                    new[] { "Γ ⊢ m : A → B", "Γ ⊢ r : B → A", "Γ ⊢ e = rm", "Γ ⊢ e = id A" },
                    new[] { "Γ ⊢ m : monomorphism C" },
                    "A split mono is monic: given a retraction r with r∘m = id A, from m∘u = m∘v we get u = r∘m∘u = r∘m∘v = v. The converse fails — not every mono splits."),
                R("Structural", "mono-marker",
                    new[] { "Γ ⊢ m : monomorphism C" }, new[] { "Γ ⊢ m : Mono" },
                    "Bridge to the built-in Mono marker, so a monomorphism proved here can be fed to the rules of the Abelian categories palette (ker-mono, mono-is-kernel and the rest)."),
            },
            null,
            new[] { "category", "monomorphism", "id" }),

        new("Chases in left R-modules",
            "Diagram chasing in the category of left R-modules, drawn rather than written. ELEMENTS are arrows out of the ring (x : R → A is the element x(1)), so applying a homomorphism is composition, 'y = fx' and 'gy = 0' are commuting triangles, and 'y lies in the image of f' is the same triangle with its first leg DASHED — the ∀∃ reading: some x makes it commute. Typings come from '[D] in Mod(R)', exactness from '[D] has exact rows', and every rule that produces an element produces it as a dashed arrow in a picture, freshly named by the engine. Only what a picture cannot say stays textual: equations between PARALLEL arrows (x = y, f = g — a commuting picture would assert them), the additive structure (x + y), and the properties injective, surjective, mono, epi. The big pictures [SES], [Sq], [Snake], [Four] are the usual ones; a chase typically starts from ONE commuting picture of the whole situation in Mod(R), and every rule then matches the sub-picture it needs.",
            new[]
            {
                // ---- elements: arrows out of the ring, and their additive structure ----
                R("Structural", "el-zero",
                    new[] { "Γ ⊢ [Obj] in Mod(R)" },
                    new[] { "Γ ⊢ 0 : Hom(R, A)" },
                    "Elements of a module are arrows out of the ring: x : R → A is the element x(1). The zero element of A is"
                    + " the zero map R → A, always available once A is in the picture."),
                R("Construction", "el-add",
                    new[] { "Γ ⊢ [Pair] in Mod(R)" },
                    new[] { "Γ ⊢ x + y : Hom(R, A)" },
                    "Two elements of A (two arrows R ⇉ A, drawn in a picture that only TYPES them — no commutativity is"
                    + " asserted) have a sum, another arrow R → A. Addition is the one structure a diagram cannot draw, so the"
                    + " sum itself stays textual."),
                R("Construction", "el-scalar",
                    new[] { "Γ ⊢ [El] in Mod(R)", "Γ ⊢ r : Hom(R, R)" },
                    new[] { "Γ ⊢ xr : Hom(R, A)" },
                    "A ring element is a map r : R → R (right multiplication by r), and the scalar multiple r·x is the"
                    + " COMPOSITE x∘r, written xr — the one place where composition order and the usual notation disagree. With"
                    + " this convention scalar multiplication is composition and every composition rule applies to it."),
                R("Computational", "add-unit",
                    new[] { "Γ ⊢ [El] in Mod(R)" },
                    new[] { "Γ ⊢ x + 0 = x", "Γ ⊢ 0 + x = x" },
                    "Zero is neutral for the sum of elements."),
                R("Computational", "add-comm",
                    new[] { "Γ ⊢ [Pair] in Mod(R)" },
                    new[] { "Γ ⊢ x + y = y + x" },
                    "Addition of elements is commutative; the picture supplies the typings x, y : R → A."),
                R("Computational", "add-assoc",
                    new[] { "Γ ⊢ [Triple] in Mod(R)", "Γ ⊢ s = x + y", "Γ ⊢ t = y + z" },
                    new[] { "Γ ⊢ s + z = x + t" },
                    "Associativity, with the inner sums named so the conclusion stays a plain equation."),
                R("Construction", "add-inverse",
                    new[] { "Γ ⊢ [El] in Mod(R)" },
                    new[] { "Γ ⊢ y : Hom(R, A)", "Γ ⊢ y + x = 0" },
                    "Every element has an additive inverse; a Construction rule, so the inverse gets a fresh name."),
                R("Computational", "add-cong",
                    new[] { "Γ ⊢ [Triple] in Mod(R)", "Γ ⊢ x = y" },
                    new[] { "Γ ⊢ x + z = y + z", "Γ ⊢ z + x = z + y" },
                    "Equal elements stay equal after adding the same thing on either side."),
                R("Elimination", "add-cancel",
                    new[] { "Γ ⊢ [Triple] in Mod(R)", "Γ ⊢ x + z = y + z" },
                    new[] { "Γ ⊢ x = y" },
                    "Cancellation — additive inverses exist, so a common summand can be removed."),
                R("Elimination", "zero-test",
                    new[] { "Γ ⊢ [Triple] in Mod(R)", "Γ ⊢ x + z = 0", "Γ ⊢ z + y = 0" },
                    new[] { "Γ ⊢ x = y" },
                    "Two elements with the same additive inverse are equal."),
                R("Elimination", "zero-module",
                    new[] { "Γ ⊢ [El] in Mod(R)", "Γ ⊢ id A = 0" },
                    new[] { "Γ ⊢ x = 0" },
                    "In the zero module every element is 0: if the identity of A is the zero map then x = (id A)x = 0."),
                // ---- homomorphisms acting on elements ----
                R("Elimination", "compose",
                    new[] { "Γ ⊢ [Row] in Mod(R)" },
                    new[] { "Γ ⊢ gf : Hom(A, C)" },
                    "Composition, read off any two consecutive arrows in a picture. Since elements are arrows this is also"
                    + " APPLICATION — fx for x : R → A is the composite — and, via el-scalar, scalar multiplication."),
                R("Introduction", "hom-ext",
                    new[] { "Γ ⊢ [Par] in Mod(R)", "Γ, x : Hom(R, A) ⊢ fx = gx" },
                    new[] { "Γ ⊢ f = g" },
                    "Extensionality: two parallel homomorphisms that agree on every element are equal. The parallel pair is"
                    + " drawn in a typing-only picture (it does not commute — that would already say f = g)."),
                R("Computational", "post-cong",
                    new[] { "Γ ⊢ [Fork] in Mod(R)", "Γ ⊢ x = y" },
                    new[] { "Γ ⊢ fx = fy" },
                    "Equal elements have equal images: congruence of composition on the left."),
                R("Computational", "pre-cong",
                    new[] { "Γ ⊢ [Pair] in Mod(R)", "Γ ⊢ r : Hom(R, R)", "Γ ⊢ x = y" },
                    new[] { "Γ ⊢ xr = yr" },
                    "Equal elements have equal scalar multiples: congruence of composition on the right."),
                R("Computational", "hom-additive",
                    new[] { "Γ ⊢ [Fork] in Mod(R)", "Γ ⊢ s = x + y" },
                    new[] { "Γ ⊢ fs = fx + fy" },
                    "A homomorphism preserves sums. The fork R ⇉ A → B only types x, y and f."),
                R("Computational", "hom-zero",
                    new[] { "Γ ⊢ [ZeroEl] in Mod(R)" },
                    new[] { "Γ ⊢ [ZeroEl] commutes in Mod(R)" },
                    "A homomorphism sends the zero element to zero: the triangle R → A → B whose two legs out of R are 0"
                    + " always commutes, i.e. f0 = 0. A picture-to-picture rule — the premise only types the triangle, the"
                    + " conclusion asserts it commutes."),
                R("Computational", "hom-linear",
                    new[] { "Γ ⊢ [Im] commutes in Mod(R)", "Γ ⊢ r : Hom(R, R)", "Γ ⊢ w = xr" },
                    new[] { "Γ ⊢ fw = yr" },
                    "A homomorphism is R-linear: f(r·x) = r·f(x). With y = fx (the commuting triangle) and w = xr this is"
                    + " associativity of composition, fw = f(xr) = (fx)r = yr."),
                R("Computational", "apply-comp",
                    new[] { "Γ ⊢ [Comp] commutes", "Γ ⊢ [Im] commutes" },
                    new[] { "Γ ⊢ [CompEl] commutes in Mod(R)" },
                    "Applying a composite: paste the triangle h = gf onto the triangle y = fx and the whole picture commutes,"
                    + " so hx = gy (and hx = gfx). Pasting in the style of the Pasting calculus palette — the conclusion is the"
                    + " glued picture, and every equation in it is then available."),
                R("Computational", "apply-id",
                    new[] { "Γ ⊢ [El] in Mod(R)", "Γ ⊢ e : Hom(A, A)", "Γ ⊢ e = id A" },
                    new[] { "Γ ⊢ ex = x" },
                    "The identity fixes every element."),
                R("Computational", "apply-zero-map",
                    new[] { "Γ ⊢ [El] in Mod(R)", "Γ ⊢ u : Hom(A, B)", "Γ ⊢ u = 0" },
                    new[] { "Γ ⊢ ux = 0" },
                    "The zero map kills every element. (Post-composing with a zero arrow is the one composite the kernel"
                    + " cannot read off a picture, since the name would begin with 0 — hence the textual form.)"),
                // ---- injective / surjective, and their equivalence with mono / epi ----
                R("Construction", "surjective-lift",
                    new[] { "Γ ⊢ [Cospan] in Mod(R)", "Γ ⊢ f : surjective" },
                    new[] { "Γ ⊢ [Im] commutes in Mod(R)" },
                    "Surjective means every element y of B has a preimage: the conclusion draws a DASHED x : R → A with fx ="
                    + " y, and the engine gives it a fresh name — the eigenvariable discipline behind every honest 'pick a"
                    + " preimage'. The same picture read as a premise, [Im] commutes, says 'y lies in the image of f'."),
                R("Elimination", "injective-cancel",
                    new[] { "Γ ⊢ [Fork] in Mod(R)", "Γ ⊢ f : injective", "Γ ⊢ fx = fy" },
                    new[] { "Γ ⊢ x = y" },
                    "Injective means equal images come from equal elements. The fork only types x, y, f; the equation fx = fy"
                    + " must be stated in text, because a commuting picture of the fork would already assert x = y."),
                R("Elimination", "injective-kills",
                    new[] { "Γ ⊢ [KillF] commutes in Mod(R)", "Γ ⊢ f : injective" },
                    new[] { "Γ ⊢ x = 0" },
                    "Injective in kernel form: the commuting triangle says fx = 0 (its second leg is the zero arrow), so x ="
                    + " 0."),
                R("Introduction", "injective-intro",
                    new[] { "Γ ⊢ [Arrow] in Mod(R)", "Γ, x : Hom(R, A), y : Hom(R, A), fx = fy ⊢ x = y" },
                    new[] { "Γ ⊢ f : injective" },
                    "To prove f injective, assume two elements with the same image and derive their equality."),
                R("Introduction", "injective-kernel-intro",
                    new[] { "Γ ⊢ [Arrow] in Mod(R)", "Γ, x : Hom(R, A), fx = 0 ⊢ x = 0" },
                    new[] { "Γ ⊢ f : injective" },
                    "The kernel criterion: a homomorphism with trivial kernel is injective."),
                R("Introduction", "surjective-intro",
                    new[] { "Γ ⊢ [Arrow] in Mod(R)", "Γ, y : Hom(R, B) ⊢ [Im] commutes" },
                    new[] { "Γ ⊢ f : surjective" },
                    "To prove f surjective, show that an arbitrary element y of B lies in the image — that the dashed-x"
                    + " triangle commutes for it."),
                R("Introduction", "mono-from-injective",
                    new[] { "Γ ⊢ [Arrow] in Mod(R)", "Γ ⊢ f : injective" },
                    new[] { "Γ ⊢ f : monomorphism" },
                    "In Mod(R) injective homomorphisms are exactly the monomorphisms (Mod(R) is concrete and R ∈ Mod(R)"
                    + " detects elements)."),
                R("Elimination", "injective-from-mono",
                    new[] { "Γ ⊢ [Arrow] in Mod(R)", "Γ ⊢ f : monomorphism" },
                    new[] { "Γ ⊢ f : injective" },
                    "The converse: a monomorphism of modules is injective — cancel against the two maps R → A picking out two"
                    + " elements with the same image."),
                R("Introduction", "epi-from-surjective",
                    new[] { "Γ ⊢ [Arrow] in Mod(R)", "Γ ⊢ f : surjective" },
                    new[] { "Γ ⊢ f : epimorphism" },
                    "Surjective homomorphisms are epimorphisms."),
                R("Elimination", "surjective-from-epi",
                    new[] { "Γ ⊢ [Arrow] in Mod(R)", "Γ ⊢ f : epimorphism" },
                    new[] { "Γ ⊢ f : surjective" },
                    "Epimorphisms of modules are surjective (compare the projection to the cokernel with the zero map)."),
                R("Structural", "injective-comp",
                    new[] { "Γ ⊢ [Row] in Mod(R)", "Γ ⊢ f : injective", "Γ ⊢ g : injective" },
                    new[] { "Γ ⊢ gf : injective" },
                    "Injective maps compose."),
                R("Structural", "surjective-comp",
                    new[] { "Γ ⊢ [Row] in Mod(R)", "Γ ⊢ f : surjective", "Γ ⊢ g : surjective" },
                    new[] { "Γ ⊢ gf : surjective" },
                    "Surjective maps compose."),
                R("Elimination", "injective-first-factor",
                    new[] { "Γ ⊢ [Comp] commutes in Mod(R)", "Γ ⊢ h : injective" },
                    new[] { "Γ ⊢ f : injective" },
                    "If the composite h = gf (the commuting triangle) is injective, so is its first factor."),
                R("Elimination", "surjective-last-factor",
                    new[] { "Γ ⊢ [Comp] commutes in Mod(R)", "Γ ⊢ h : surjective" },
                    new[] { "Γ ⊢ g : surjective" },
                    "If the composite h = gf is surjective, so is its last factor."),
                // ---- exactness, read off pictures ----
                R("Elimination", "exact-complex",
                    new[] { "Γ ⊢ [Row] has exact rows in Mod(R)" },
                    new[] { "Γ ⊢ [CompZ] commutes in Mod(R)" },
                    "Exact at B implies gf = 0: the triangle A → B → C with the zero arrow A → C commutes. One premise — 'has"
                    + " exact rows in Mod(R)' supplies both the typings of the row and exact(f, g)."),
                R("Computational", "complex-kills",
                    new[] { "Γ ⊢ [CompZ] commutes", "Γ ⊢ [Im] commutes in Mod(R)" },
                    new[] { "Γ ⊢ [Kill] commutes in Mod(R)" },
                    "The easy half of exactness on elements: if gf = 0 and y = fx (y lies in the image of f) then gy = 0 —"
                    + " the triangle R → B → C with the zero leg commutes."),
                R("Construction", "exact-lift",
                    new[] { "Γ ⊢ [Row] has exact rows in Mod(R)", "Γ ⊢ [Kill] commutes in Mod(R)" },
                    new[] { "Γ ⊢ [Im] commutes in Mod(R)" },
                    "The hard half: exact at B and gy = 0 (the commuting Kill triangle) give a preimage — the DASHED x : R →"
                    + " A with fx = y, freshly named by the engine because the preimage is not unique."),
                R("Introduction", "exact-intro",
                    new[] { "Γ ⊢ [Row] in Mod(R)",
                        "Γ, y : Hom(R, B), [Im] commutes ⊢ [Kill] commutes",
                        "Γ, y : Hom(R, B), [Kill] commutes ⊢ [Im] commutes" },
                    new[] { "Γ ⊢ [Row] has exact rows" },
                    "Exactness at B is the two inclusions im f ⊆ ker g and ker g ⊆ im f, each stated as a hypothetical"
                    + " judgment on an arbitrary element y: from 'y in the image' (Im commutes) derive 'g kills y' (Kill"
                    + " commutes), and back."),
                R("Introduction", "complex-intro",
                    new[] { "Γ ⊢ [Row] in Mod(R)", "Γ, x : Hom(R, A) ⊢ gfx = 0" },
                    new[] { "Γ ⊢ [CompZ] commutes in Mod(R)" },
                    "To prove gf = 0 kill an arbitrary element: sound because homomorphisms of modules are determined by"
                    + " their values on elements."),
                R("Elimination", "exact-at-zero-left",
                    new[] { "Γ ⊢ [ZeroRowL] has exact rows in Mod(R)" },
                    new[] { "Γ ⊢ f : injective" },
                    "Exactness at the left end of 0 → A → B: the image of the zero arrow is {0}, so ker f = {0} and f is"
                    + " injective. This is what a drawn short exact sequence asserts at A."),
                R("Introduction", "injective-exact-left",
                    new[] { "Γ ⊢ [ZeroRowL] in Mod(R)", "Γ ⊢ f : injective" },
                    new[] { "Γ ⊢ [ZeroRowL] has exact rows" },
                    "The converse: an injective f makes 0 → A → B exact at A."),
                R("Elimination", "exact-at-zero-right",
                    new[] { "Γ ⊢ [ZeroRowR] has exact rows in Mod(R)" },
                    new[] { "Γ ⊢ g : surjective" },
                    "Exactness at the right end of B → C → 0: the kernel of the zero arrow is all of C, so im g = C and g is"
                    + " surjective."),
                R("Introduction", "surjective-exact-right",
                    new[] { "Γ ⊢ [ZeroRowR] in Mod(R)", "Γ ⊢ g : surjective" },
                    new[] { "Γ ⊢ [ZeroRowR] has exact rows" },
                    "The converse: a surjective g makes B → C → 0 exact at C."),
                R("Elimination", "ses-elim",
                    new[] { "Γ ⊢ [SES] has exact rows in Mod(R)" },
                    new[] { "Γ ⊢ f : injective",
                        "Γ ⊢ g : surjective",
                        "Γ ⊢ f : monomorphism",
                        "Γ ⊢ g : epimorphism",
                        "Γ ⊢ gf = 0" },
                    "A short exact sequence 0 → A → B → C → 0, drawn, unpacked into what a chase uses: exact(0, f) is f"
                    + " injective, exact(g, 0) is g surjective, exact(f, g) makes the composite vanish, and in Mod(R)"
                    + " injective/surjective upgrade to mono/epi."),
                // ---- the chase moves themselves ----
                R("Structural", "eq-trans",
                    new[] { "Γ ⊢ x = y", "Γ ⊢ y = z" },
                    new[] { "Γ ⊢ x = z" },
                    "Chaining equalities (symmetry is built into the kernel's matching of equations)."),
                R("Computational", "difference-in-kernel",
                    new[] { "Γ ⊢ [Fork3] in Mod(R)", "Γ ⊢ d + y = x", "Γ ⊢ fx = fy" },
                    new[] { "Γ ⊢ fd = 0" },
                    "Two elements with the same image differ by an element of the kernel: with d = x − y (written d + y = x),"
                    + " fd = fx − fy = 0."),
                R("Computational", "kernel-shift",
                    new[] { "Γ ⊢ [Fork3] in Mod(R)", "Γ ⊢ d + y = x", "Γ ⊢ fd = 0" },
                    new[] { "Γ ⊢ fx = fy" },
                    "The converse: shifting by a kernel element does not change the image."),
                R("Theorem", "connecting-step",
                    new[] { "Γ ⊢ [SqB] commutes", "Γ ⊢ [KillC] commutes" },
                    new[] { "Γ ⊢ [KillD] commutes in Mod(R)" },
                    "The step at the heart of every connecting-morphism argument: in the commuting square mg = kn with"
                    + " elements b, c = gb and d = nb drawn in, if m kills c then k kills d — kd = knb = mgb = mc = 0. Two"
                    + " pictures in, one picture out."),
                R("Computational", "sq-eq",
                    new[] { "Γ ⊢ [Sq] commutes" },
                    new[] { "Γ ⊢ bf = ga" },
                    "The equation a commuting square asserts, read off literally (the picture already supplies it as a"
                    + " derived judgment; this rule makes it a step)."),
                R("Computational", "sq-chase",
                    new[] { "Γ ⊢ [Sq] commutes", "Γ ⊢ [ImF] commutes", "Γ ⊢ [ImA] commutes" },
                    new[] { "Γ ⊢ [SqEl] commutes in Mod(R)" },
                    "Chasing an element around a commuting square: with u = fx and v = ax the whole picture with the element"
                    + " drawn in commutes, so bu = gv. Pasting: the conclusion is the square with x, u, v glued on."),
                R("Construction", "snake-connect",
                    new[] { "Γ ⊢ [SnakeEl] commutes in Mod(R)", "Γ ⊢ [RowST] has exact rows", "Γ ⊢ [KillZ] commutes" },
                    new[] { "Γ ⊢ [ImS] commutes in Mod(R)" },
                    "The connecting homomorphism, one step: in the snake picture with the elements y : R → B, z = qy and w ="
                    + " by drawn in, if c kills z then tw = cz = 0, so by exactness of the bottom row at E the element w lifts"
                    + " along s — the DASHED x : R → D with sx = w, freshly named. Three pictures in, one picture out (it was"
                    + " twelve premises)."),
                R("Theorem", "four-lemma-mono",
                    new[] { "Γ ⊢ [Four] commutes",
                        "Γ ⊢ [Four] has exact rows",
                        "Γ ⊢ a : surjective",
                        "Γ ⊢ b : injective",
                        "Γ ⊢ d : injective" },
                    new[] { "Γ ⊢ c : injective", "Γ ⊢ c : monomorphism" },
                    "The sharp four lemma: in the ladder with exact rows, a epi and b, d mono force c mono. The picture"
                    + " supplies the ten arrows, the three squares and the four exactness facts; only what no picture can say —"
                    + " a epi, b and d mono — is stated, and every hypothesis is used in the chase."),
            },
            new[]
            {
                ("Obj", "[0, 1, [0,0,\"A\"]]"),
                ("Arrow", "[0, 2, [0,0,\"A\"], [1,0,\"B\"], [0,1,\"f\"]]"),
                ("Par", "[0, 2, [0,0,\"A\"], [1,0,\"B\"], [0,1,\"f\",0,{\"curve\":-2}], [0,1,\"g\",2,{\"curve\":2}]]"),
                ("El", "[0, 2, [0,0,\"R\"], [1,0,\"A\"], [0,1,\"x\"]]"),
                ("Pair", "[0, 2, [0,0,\"R\"], [1,0,\"A\"], [0,1,\"x\",0,{\"curve\":-2}], [0,1,\"y\",2,{\"curve\":2}]]"),
                ("Triple", "[0, 2, [0,0,\"R\"], [1,0,\"A\"], [0,1,\"x\",0,{\"curve\":-3}], [0,1,\"y\"], [0,1,\"z\",2,{\"curve\":3}]]"),
                ("Row", "[0, 3, [0,0,\"A\"], [1,0,\"B\"], [2,0,\"C\"], [0,1,\"f\"], [1,2,\"g\"]]"),
                ("Comp", "[0, 3, [0,0,\"A\"], [1,0,\"B\"], [2,0,\"C\"], [0,1,\"f\"], [1,2,\"g\"], [0,2,\"h\",2,{\"curve\":3}]]"),
                ("CompZ", "[0, 3, [0,0,\"A\"], [1,0,\"B\"], [2,0,\"C\"], [0,1,\"f\"], [1,2,\"g\"], [0,2,\"0\",2,{\"curve\":3}]]"),
                ("Cospan", "[0, 3, [1,0,\"R\"], [0,1,\"A\"], [1,1,\"B\"], [1,2,\"f\"], [0,2,\"y\"]]"),
                ("Im", "[0, 3, [1,0,\"R\"], [0,1,\"A\"], [1,1,\"B\"], [0,1,\"x\",0,{\"style\":{\"body\":{\"name\":\"dashed\"}}}], [1,2,\"f\"], [0,2,\"y\"]]"),
                ("KillF", "[0, 3, [1,0,\"R\"], [0,1,\"A\"], [1,1,\"B\"], [0,1,\"x\"], [1,2,\"f\"], [0,2,\"0\"]]"),
                ("Kill", "[0, 3, [1,0,\"R\"], [0,1,\"B\"], [1,1,\"C\"], [0,1,\"y\"], [1,2,\"g\"], [0,2,\"0\"]]"),
                ("ZeroEl", "[0, 3, [0,0,\"R\"], [1,0,\"A\"], [2,0,\"B\"], [0,1,\"0\"], [1,2,\"f\"], [0,2,\"0\",2,{\"curve\":3}]]"),
                ("Fork", "[0, 3, [0,0,\"R\"], [1,0,\"A\"], [2,0,\"B\"], [0,1,\"x\",0,{\"curve\":-2}], [0,1,\"y\",2,{\"curve\":2}], [1,2,\"f\"]]"),
                ("Fork3", "[0, 3, [0,0,\"R\"], [1,0,\"A\"], [2,0,\"B\"], [0,1,\"x\",0,{\"curve\":-3}], [0,1,\"y\"], [0,1,\"d\",2,{\"curve\":3}], [1,2,\"f\"]]"),
                ("CompEl", "[0, 4, [1,0,\"R\"], [0,1,\"A\"], [1,1,\"B\"], [2,1,\"C\"], [0,1,\"x\"], [0,2,\"y\"], [1,2,\"f\"], [2,3,\"g\"], [1,3,\"h\",2,{\"curve\":3}]]"),
                ("ZeroRowL", "[0, 3, [0,0,\"0\"], [1,0,\"A\"], [2,0,\"B\"], [0,1,\"0\"], [1,2,\"f\"]]"),
                ("ZeroRowR", "[0, 3, [0,0,\"B\"], [1,0,\"C\"], [2,0,\"0\"], [0,1,\"g\"], [1,2,\"0\"]]"),
                ("SES", "[0, 5, [0,0,\"0\"], [1,0,\"A\"], [2,0,\"B\"], [3,0,\"C\"], [4,0,\"0\"], [0,1,\"0\"], [1,2,\"f\"], [2,3,\"g\"], [3,4,\"0\"]]"),
                ("Sq", "[0, 4, [0,0,\"A\"], [1,0,\"B\"], [0,1,\"C\"], [1,1,\"D\"], [0,1,\"f\"], [0,2,\"a\"], [1,3,\"b\"], [2,3,\"g\"]]"),
                ("ImF", "[0, 3, [1,0,\"R\"], [0,1,\"A\"], [1,1,\"B\"], [0,1,\"x\"], [1,2,\"f\"], [0,2,\"u\"]]"),
                ("ImA", "[0, 3, [1,0,\"R\"], [0,1,\"A\"], [1,1,\"C\"], [0,1,\"x\"], [1,2,\"a\"], [0,2,\"v\"]]"),
                ("SqEl", "[0, 5, [0,0,\"R\"], [1,1,\"A\"], [2,1,\"B\"], [1,2,\"C\"], [2,2,\"D\"], [0,1,\"x\"], [0,2,\"u\",0,{\"curve\":-2}], [0,3,\"v\",2,{\"curve\":2}], [1,2,\"f\"], [1,3,\"a\"], [2,4,\"b\"], [3,4,\"g\"]]"),
                ("SqB", "[0, 5, [0,0,\"R\"], [0,1,\"B\"], [1,1,\"C\"], [0,2,\"D\"], [1,2,\"E\"], [0,1,\"b\"], [0,2,\"c\"], [0,3,\"d\",2,{\"curve\":3}], [1,2,\"g\"], [1,3,\"n\"], [2,4,\"m\"], [3,4,\"k\"]]"),
                ("KillC", "[0, 3, [1,0,\"R\"], [0,1,\"C\"], [1,1,\"E\"], [0,1,\"c\"], [1,2,\"m\"], [0,2,\"0\"]]"),
                ("KillD", "[0, 3, [1,0,\"R\"], [0,1,\"D\"], [1,1,\"E\"], [0,1,\"d\"], [1,2,\"k\"], [0,2,\"0\"]]"),
                ("Snake", "[0, 8, [1,0,\"A\"], [2,0,\"B\"], [3,0,\"C\"], [4,0,\"0\"], [0,1,\"0\"], [1,1,\"D\"], [2,1,\"E\"], [3,1,\"F\"], [0,1,\"p\"], [1,2,\"q\"], [2,3,\"0\"], [4,5,\"0\"], [5,6,\"s\"], [6,7,\"t\"], [0,5,\"a\"], [1,6,\"b\"], [2,7,\"c\"]]"),
                ("SnakeEl", "[0, 9, [1,0,\"A\"], [2,0,\"B\"], [3,0,\"C\"], [4,0,\"0\"], [0,1,\"0\"], [1,1,\"D\"], [2,1,\"E\"], [3,1,\"F\"], [2,2,\"R\"], [0,1,\"p\"], [1,2,\"q\"], [2,3,\"0\"], [4,5,\"0\"], [5,6,\"s\"], [6,7,\"t\"], [0,5,\"a\"], [1,6,\"b\"], [2,7,\"c\"], [8,1,\"y\",0,{\"curve\":-2}], [8,2,\"z\",2,{\"curve\":2}], [8,6,\"w\"]]"),
                ("KillZ", "[0, 3, [1,0,\"R\"], [0,1,\"C\"], [1,1,\"F\"], [0,1,\"z\"], [1,2,\"c\"], [0,2,\"0\"]]"),
                ("ImS", "[0, 3, [1,0,\"R\"], [0,1,\"D\"], [1,1,\"E\"], [0,1,\"x\",0,{\"style\":{\"body\":{\"name\":\"dashed\"}}}], [1,2,\"s\"], [0,2,\"w\"]]"),
                ("RowST", "[0, 3, [0,0,\"D\"], [1,0,\"E\"], [2,0,\"F\"], [0,1,\"s\"], [1,2,\"t\"]]"),
                ("Four", "[0, 8, [0,0,\"A\"], [1,0,\"B\"], [2,0,\"C\"], [3,0,\"D\"], [0,1,\"E\"], [1,1,\"F\"], [2,1,\"G\"], [3,1,\"H\"], [0,1,\"p\"], [1,2,\"q\"], [2,3,\"r\"], [4,5,\"u\"], [5,6,\"v\"], [6,7,\"w\"], [0,4,\"a\"], [1,5,\"b\"], [2,6,\"c\"], [3,7,\"d\"]]"),
            },
            new[] { "Hom", "Mod", "Ring", "epimorphism", "exact", "id", "injective", "monomorphism", "surjective" }),

        new("Poset as a category",
            "The functor from posets to thin categories: elements are objects, x ≤ y is the unique arrow x → y. Reflexivity gives identities, transitivity gives composition, and thinness makes every diagram commute. (Antisymmetry corresponds to skeletality — mutually connected objects coincide — which lives outside the syntax as a side condition.)",
            new[]
            {
                R("Structural", "objects", None, new[] { "P : Type, x : P ⊢ x : P" },
                    "Each element of the poset is an object of the category."),
                R("Construction", "refl-id", None, new[] { "P : Type, x : P ⊢ idₓ : x → x" },
                    "Reflexivity x ≤ x becomes the identity arrow: hom(x, x) is inhabited."),
                R("Elimination", "trans-compose",
                    new[] { "Γ ⊢ f : x → y", "Γ ⊢ g : y → z" }, new[] { "Γ ⊢ gf : x → z" },
                    "Transitivity (x ≤ y and y ≤ z imply x ≤ z) becomes composition; gf stands for g ∘ f."),
                R("Computational", "thinness",
                    new[] { "Γ ⊢ f : x → y", "Γ ⊢ g : x → y" }, new[] { "Γ ⊢ [Par] commutes" },
                    "At most one arrow between any two objects: any parallel pair is equal, so every diagram in a poset-category commutes."),
                R("Structural", "point-commutes", None, new[] { "C : Type, X : C ⊢ [Pt] commutes" },
                    "A single-object diagram — no arrows, not even the identity drawn — commutes vacuously: there is no pair of parallel composites to compare."),
            },
            new[]
            {
                ("Pt", "[0, 1, [0,0,\"X\"]]"),
                ("Par", "[0, 2, [0,0,\"x\"], [1,0,\"y\"], [0,1,\"f\"], [0,1,\"g\",2,{\"curve\":2}]]"),
            }),

        new("Linear logic (fragment)",
            "Resource-sensitive sequent calculus: × read as ⊗, + as ⊕, ∩ as & — multiplicative rules SPLIT the context (Γ, Δ), additive rules SHARE it; no weakening or contraction.",
            new[]
            {
                R("Structural", "axiom", None, new[] { "x : σ ⊢ x : σ" },
                    "Identity: exactly one hypothesis, used exactly once — the whole context is the single resource."),
                R("Introduction", "⊸-intro", new[] { "Γ, x : σ ⊢ M : τ" }, new[] { "Γ ⊢ λxM : σ → τ" },
                    "Linear abstraction: the body must use x exactly once."),
                R("Elimination", "⊸-elim", new[] { "Γ ⊢ f : σ → τ", "Δ ⊢ a : σ" }, new[] { "Γ, Δ ⊢ fa : τ" },
                    "Linear application — multiplicative: the function and argument consume disjoint resources Γ and Δ."),
                R("Introduction", "⊗-intro", new[] { "Γ ⊢ M : σ", "Δ ⊢ N : τ" }, new[] { "Γ, Δ ⊢ MN : σ × τ" },
                    "Tensor — multiplicative: the pair's components draw on disjoint contexts, both consumed."),
                R("Elimination", "⊗-elim", new[] { "Γ ⊢ p : σ × τ", "Δ, x : σ, y : τ ⊢ N : ρ" }, new[] { "Γ, Δ ⊢ M : ρ" },
                    "Tensor elimination: let (x, y) = p in N — both components must be used."),
                R("Introduction", "&-intro", new[] { "Γ ⊢ M : σ", "Γ ⊢ N : τ" }, new[] { "Γ ⊢ MN : σ ∩ τ" },
                    "With — additive: BOTH alternatives are offered from the SAME resources Γ; the consumer will pick one."),
                R("Elimination", "&-elim1", new[] { "Γ ⊢ p : σ ∩ τ" }, new[] { "Γ ⊢ p1 : σ" },
                    "Choose the left alternative."),
                R("Elimination", "&-elim2", new[] { "Γ ⊢ p : σ ∩ τ" }, new[] { "Γ ⊢ p2 : τ" },
                    "Choose the right alternative."),
                R("Introduction", "⊕-intro1", new[] { "Γ ⊢ M : σ" }, new[] { "Γ ⊢ M : σ + τ" },
                    "Left injection into the plus."),
                R("Introduction", "⊕-intro2", new[] { "Γ ⊢ M : τ" }, new[] { "Γ ⊢ M : σ + τ" },
                    "Right injection into the plus."),
                R("Elimination", "⊕-elim",
                    new[] { "Γ ⊢ M : σ + τ", "Δ, x : σ ⊢ N1 : ρ", "Δ, y : τ ⊢ N2 : ρ" }, new[] { "Γ, Δ ⊢ N : ρ" },
                    "Case analysis: whichever branch fires consumes Δ plus its injected component exactly once."),
            }),
    };
}
